// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.12
// source: dcs/hook/v0/hook.proto

package hook

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMissionNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMissionNameRequest) Reset() {
	*x = GetMissionNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMissionNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMissionNameRequest) ProtoMessage() {}

func (x *GetMissionNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMissionNameRequest.ProtoReflect.Descriptor instead.
func (*GetMissionNameRequest) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{0}
}

type GetMissionNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetMissionNameResponse) Reset() {
	*x = GetMissionNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMissionNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMissionNameResponse) ProtoMessage() {}

func (x *GetMissionNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMissionNameResponse.ProtoReflect.Descriptor instead.
func (*GetMissionNameResponse) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{1}
}

func (x *GetMissionNameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetMissionFilenameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMissionFilenameRequest) Reset() {
	*x = GetMissionFilenameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMissionFilenameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMissionFilenameRequest) ProtoMessage() {}

func (x *GetMissionFilenameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMissionFilenameRequest.ProtoReflect.Descriptor instead.
func (*GetMissionFilenameRequest) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{2}
}

type GetMissionFilenameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetMissionFilenameResponse) Reset() {
	*x = GetMissionFilenameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMissionFilenameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMissionFilenameResponse) ProtoMessage() {}

func (x *GetMissionFilenameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMissionFilenameResponse.ProtoReflect.Descriptor instead.
func (*GetMissionFilenameResponse) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{3}
}

func (x *GetMissionFilenameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetMissionDescriptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMissionDescriptionRequest) Reset() {
	*x = GetMissionDescriptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMissionDescriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMissionDescriptionRequest) ProtoMessage() {}

func (x *GetMissionDescriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMissionDescriptionRequest.ProtoReflect.Descriptor instead.
func (*GetMissionDescriptionRequest) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{4}
}

type GetMissionDescriptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *GetMissionDescriptionResponse) Reset() {
	*x = GetMissionDescriptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMissionDescriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMissionDescriptionResponse) ProtoMessage() {}

func (x *GetMissionDescriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMissionDescriptionResponse.ProtoReflect.Descriptor instead.
func (*GetMissionDescriptionResponse) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{5}
}

func (x *GetMissionDescriptionResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetPausedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPausedRequest) Reset() {
	*x = GetPausedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPausedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPausedRequest) ProtoMessage() {}

func (x *GetPausedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPausedRequest.ProtoReflect.Descriptor instead.
func (*GetPausedRequest) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{6}
}

type GetPausedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paused bool `protobuf:"varint,1,opt,name=paused,proto3" json:"paused,omitempty"`
}

func (x *GetPausedResponse) Reset() {
	*x = GetPausedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPausedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPausedResponse) ProtoMessage() {}

func (x *GetPausedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPausedResponse.ProtoReflect.Descriptor instead.
func (*GetPausedResponse) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{7}
}

func (x *GetPausedResponse) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

type SetPausedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paused bool `protobuf:"varint,1,opt,name=paused,proto3" json:"paused,omitempty"`
}

func (x *SetPausedRequest) Reset() {
	*x = SetPausedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetPausedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPausedRequest) ProtoMessage() {}

func (x *SetPausedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPausedRequest.ProtoReflect.Descriptor instead.
func (*SetPausedRequest) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{8}
}

func (x *SetPausedRequest) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

type SetPausedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetPausedResponse) Reset() {
	*x = SetPausedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetPausedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPausedResponse) ProtoMessage() {}

func (x *SetPausedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPausedResponse.ProtoReflect.Descriptor instead.
func (*SetPausedResponse) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{9}
}

type ReloadCurrentMissionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReloadCurrentMissionRequest) Reset() {
	*x = ReloadCurrentMissionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReloadCurrentMissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadCurrentMissionRequest) ProtoMessage() {}

func (x *ReloadCurrentMissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadCurrentMissionRequest.ProtoReflect.Descriptor instead.
func (*ReloadCurrentMissionRequest) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{10}
}

type ReloadCurrentMissionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReloadCurrentMissionResponse) Reset() {
	*x = ReloadCurrentMissionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReloadCurrentMissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadCurrentMissionResponse) ProtoMessage() {}

func (x *ReloadCurrentMissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadCurrentMissionResponse.ProtoReflect.Descriptor instead.
func (*ReloadCurrentMissionResponse) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{11}
}

type LoadNextMissionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LoadNextMissionRequest) Reset() {
	*x = LoadNextMissionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadNextMissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadNextMissionRequest) ProtoMessage() {}

func (x *LoadNextMissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadNextMissionRequest.ProtoReflect.Descriptor instead.
func (*LoadNextMissionRequest) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{12}
}

type LoadNextMissionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Was the next mission successfully loaded. SHOULD return false when the
	// end of the mission list has been reached but DCS appears to always
	// return true
	Loaded bool `protobuf:"varint,1,opt,name=loaded,proto3" json:"loaded,omitempty"`
}

func (x *LoadNextMissionResponse) Reset() {
	*x = LoadNextMissionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadNextMissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadNextMissionResponse) ProtoMessage() {}

func (x *LoadNextMissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadNextMissionResponse.ProtoReflect.Descriptor instead.
func (*LoadNextMissionResponse) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{13}
}

func (x *LoadNextMissionResponse) GetLoaded() bool {
	if x != nil {
		return x.Loaded
	}
	return false
}

type LoadMissionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The full path to the .miz file to be loaded
	FileName string `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
}

func (x *LoadMissionRequest) Reset() {
	*x = LoadMissionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadMissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadMissionRequest) ProtoMessage() {}

func (x *LoadMissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadMissionRequest.ProtoReflect.Descriptor instead.
func (*LoadMissionRequest) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{14}
}

func (x *LoadMissionRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type LoadMissionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LoadMissionResponse) Reset() {
	*x = LoadMissionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadMissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadMissionResponse) ProtoMessage() {}

func (x *LoadMissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadMissionResponse.ProtoReflect.Descriptor instead.
func (*LoadMissionResponse) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{15}
}

type StopMissionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopMissionRequest) Reset() {
	*x = StopMissionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopMissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopMissionRequest) ProtoMessage() {}

func (x *StopMissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopMissionRequest.ProtoReflect.Descriptor instead.
func (*StopMissionRequest) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{16}
}

type StopMissionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopMissionResponse) Reset() {
	*x = StopMissionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopMissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopMissionResponse) ProtoMessage() {}

func (x *StopMissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopMissionResponse.ProtoReflect.Descriptor instead.
func (*StopMissionResponse) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{17}
}

type EvalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lua string `protobuf:"bytes,1,opt,name=lua,proto3" json:"lua,omitempty"`
}

func (x *EvalRequest) Reset() {
	*x = EvalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvalRequest) ProtoMessage() {}

func (x *EvalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvalRequest.ProtoReflect.Descriptor instead.
func (*EvalRequest) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{18}
}

func (x *EvalRequest) GetLua() string {
	if x != nil {
		return x.Lua
	}
	return ""
}

type EvalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Json string `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
}

func (x *EvalResponse) Reset() {
	*x = EvalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvalResponse) ProtoMessage() {}

func (x *EvalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvalResponse.ProtoReflect.Descriptor instead.
func (*EvalResponse) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{19}
}

func (x *EvalResponse) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

type ExitProcessRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ExitProcessRequest) Reset() {
	*x = ExitProcessRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExitProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitProcessRequest) ProtoMessage() {}

func (x *ExitProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitProcessRequest.ProtoReflect.Descriptor instead.
func (*ExitProcessRequest) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{20}
}

type ExitProcessResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ExitProcessResponse) Reset() {
	*x = ExitProcessResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExitProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitProcessResponse) ProtoMessage() {}

func (x *ExitProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitProcessResponse.ProtoReflect.Descriptor instead.
func (*ExitProcessResponse) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{21}
}

type IsMultiplayerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IsMultiplayerRequest) Reset() {
	*x = IsMultiplayerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsMultiplayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsMultiplayerRequest) ProtoMessage() {}

func (x *IsMultiplayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsMultiplayerRequest.ProtoReflect.Descriptor instead.
func (*IsMultiplayerRequest) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{22}
}

type IsMultiplayerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Multiplayer bool `protobuf:"varint,1,opt,name=multiplayer,proto3" json:"multiplayer,omitempty"`
}

func (x *IsMultiplayerResponse) Reset() {
	*x = IsMultiplayerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsMultiplayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsMultiplayerResponse) ProtoMessage() {}

func (x *IsMultiplayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsMultiplayerResponse.ProtoReflect.Descriptor instead.
func (*IsMultiplayerResponse) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{23}
}

func (x *IsMultiplayerResponse) GetMultiplayer() bool {
	if x != nil {
		return x.Multiplayer
	}
	return false
}

type IsServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IsServerRequest) Reset() {
	*x = IsServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsServerRequest) ProtoMessage() {}

func (x *IsServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsServerRequest.ProtoReflect.Descriptor instead.
func (*IsServerRequest) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{24}
}

type IsServerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Server bool `protobuf:"varint,1,opt,name=server,proto3" json:"server,omitempty"`
}

func (x *IsServerResponse) Reset() {
	*x = IsServerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsServerResponse) ProtoMessage() {}

func (x *IsServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsServerResponse.ProtoReflect.Descriptor instead.
func (*IsServerResponse) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{25}
}

func (x *IsServerResponse) GetServer() bool {
	if x != nil {
		return x.Server
	}
	return false
}

type BanPlayerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The session ID of the player
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The period of the ban in seconds
	Period uint32 `protobuf:"varint,2,opt,name=period,proto3" json:"period,omitempty"`
	// The reason for the ban
	Reason string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *BanPlayerRequest) Reset() {
	*x = BanPlayerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BanPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanPlayerRequest) ProtoMessage() {}

func (x *BanPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanPlayerRequest.ProtoReflect.Descriptor instead.
func (*BanPlayerRequest) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{26}
}

func (x *BanPlayerRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BanPlayerRequest) GetPeriod() uint32 {
	if x != nil {
		return x.Period
	}
	return 0
}

func (x *BanPlayerRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type BanPlayerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Was the player successfully banned
	Banned bool `protobuf:"varint,1,opt,name=banned,proto3" json:"banned,omitempty"`
}

func (x *BanPlayerResponse) Reset() {
	*x = BanPlayerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BanPlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanPlayerResponse) ProtoMessage() {}

func (x *BanPlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanPlayerResponse.ProtoReflect.Descriptor instead.
func (*BanPlayerResponse) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{27}
}

func (x *BanPlayerResponse) GetBanned() bool {
	if x != nil {
		return x.Banned
	}
	return false
}

type UnbanPlayerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The globally unique ID of the player
	Ucid string `protobuf:"bytes,1,opt,name=ucid,proto3" json:"ucid,omitempty"`
}

func (x *UnbanPlayerRequest) Reset() {
	*x = UnbanPlayerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnbanPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanPlayerRequest) ProtoMessage() {}

func (x *UnbanPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanPlayerRequest.ProtoReflect.Descriptor instead.
func (*UnbanPlayerRequest) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{28}
}

func (x *UnbanPlayerRequest) GetUcid() string {
	if x != nil {
		return x.Ucid
	}
	return ""
}

type UnbanPlayerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Was the player successfully unbanned
	Unbanned bool `protobuf:"varint,1,opt,name=unbanned,proto3" json:"unbanned,omitempty"`
}

func (x *UnbanPlayerResponse) Reset() {
	*x = UnbanPlayerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnbanPlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanPlayerResponse) ProtoMessage() {}

func (x *UnbanPlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanPlayerResponse.ProtoReflect.Descriptor instead.
func (*UnbanPlayerResponse) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{29}
}

func (x *UnbanPlayerResponse) GetUnbanned() bool {
	if x != nil {
		return x.Unbanned
	}
	return false
}

type GetBannedPlayersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetBannedPlayersRequest) Reset() {
	*x = GetBannedPlayersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBannedPlayersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBannedPlayersRequest) ProtoMessage() {}

func (x *GetBannedPlayersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBannedPlayersRequest.ProtoReflect.Descriptor instead.
func (*GetBannedPlayersRequest) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{30}
}

type GetBannedPlayersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bans []*BanDetails `protobuf:"bytes,1,rep,name=bans,proto3" json:"bans,omitempty"`
}

func (x *GetBannedPlayersResponse) Reset() {
	*x = GetBannedPlayersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBannedPlayersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBannedPlayersResponse) ProtoMessage() {}

func (x *GetBannedPlayersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBannedPlayersResponse.ProtoReflect.Descriptor instead.
func (*GetBannedPlayersResponse) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{31}
}

func (x *GetBannedPlayersResponse) GetBans() []*BanDetails {
	if x != nil {
		return x.Bans
	}
	return nil
}

type BanDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The globally unique ID of the player
	Ucid string `protobuf:"bytes,1,opt,name=ucid,proto3" json:"ucid,omitempty"`
	// The IP address the user had when they were banned
	IpAddress string `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// The Name of the player at the time of the ban
	PlayerName string `protobuf:"bytes,3,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	// The reason given for the ban
	Reason string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	// When the ban was issued in unixtime
	BannedFrom uint64 `protobuf:"varint,5,opt,name=banned_from,json=bannedFrom,proto3" json:"banned_from,omitempty"`
	// When the ban will expire in unixtime
	BannedUntil uint64 `protobuf:"varint,6,opt,name=banned_until,json=bannedUntil,proto3" json:"banned_until,omitempty"`
}

func (x *BanDetails) Reset() {
	*x = BanDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BanDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanDetails) ProtoMessage() {}

func (x *BanDetails) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanDetails.ProtoReflect.Descriptor instead.
func (*BanDetails) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{32}
}

func (x *BanDetails) GetUcid() string {
	if x != nil {
		return x.Ucid
	}
	return ""
}

func (x *BanDetails) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *BanDetails) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *BanDetails) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *BanDetails) GetBannedFrom() uint64 {
	if x != nil {
		return x.BannedFrom
	}
	return 0
}

func (x *BanDetails) GetBannedUntil() uint64 {
	if x != nil {
		return x.BannedUntil
	}
	return 0
}

type GetUnitTypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The slot or unit ID of the unit to retrieve the type of
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetUnitTypeRequest) Reset() {
	*x = GetUnitTypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUnitTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnitTypeRequest) ProtoMessage() {}

func (x *GetUnitTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnitTypeRequest.ProtoReflect.Descriptor instead.
func (*GetUnitTypeRequest) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{33}
}

func (x *GetUnitTypeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUnitTypeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Type of unit (e.g. "F-14B")
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *GetUnitTypeResponse) Reset() {
	*x = GetUnitTypeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUnitTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnitTypeResponse) ProtoMessage() {}

func (x *GetUnitTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnitTypeResponse.ProtoReflect.Descriptor instead.
func (*GetUnitTypeResponse) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{34}
}

func (x *GetUnitTypeResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetRealTimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetRealTimeRequest) Reset() {
	*x = GetRealTimeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[35]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRealTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRealTimeRequest) ProtoMessage() {}

func (x *GetRealTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[35]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRealTimeRequest.ProtoReflect.Descriptor instead.
func (*GetRealTimeRequest) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{35}
}

type GetRealTimeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The current time in a mission relative to the DCS start time
	Time float64 `protobuf:"fixed64,1,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *GetRealTimeResponse) Reset() {
	*x = GetRealTimeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[36]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRealTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRealTimeResponse) ProtoMessage() {}

func (x *GetRealTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[36]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRealTimeResponse.ProtoReflect.Descriptor instead.
func (*GetRealTimeResponse) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{36}
}

func (x *GetRealTimeResponse) GetTime() float64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type GetBallisticsCountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetBallisticsCountRequest) Reset() {
	*x = GetBallisticsCountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[37]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBallisticsCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBallisticsCountRequest) ProtoMessage() {}

func (x *GetBallisticsCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[37]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBallisticsCountRequest.ProtoReflect.Descriptor instead.
func (*GetBallisticsCountRequest) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{37}
}

type GetBallisticsCountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count uint32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GetBallisticsCountResponse) Reset() {
	*x = GetBallisticsCountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_hook_v0_hook_proto_msgTypes[38]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBallisticsCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBallisticsCountResponse) ProtoMessage() {}

func (x *GetBallisticsCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_hook_v0_hook_proto_msgTypes[38]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBallisticsCountResponse.ProtoReflect.Descriptor instead.
func (*GetBallisticsCountResponse) Descriptor() ([]byte, []int) {
	return file_dcs_hook_v0_hook_proto_rawDescGZIP(), []int{38}
}

func (x *GetBallisticsCountResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_dcs_hook_v0_hook_proto protoreflect.FileDescriptor

var file_dcs_hook_v0_hook_proto_rawDesc = []byte{
	0x0a, 0x16, 0x64, 0x63, 0x73, 0x2f, 0x68, 0x6f, 0x6f, 0x6b, 0x2f, 0x76, 0x30, 0x2f, 0x68, 0x6f,
	0x6f, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x64, 0x63, 0x73, 0x2e, 0x68, 0x6f,
	0x6f, 0x6b, 0x2e, 0x76, 0x30, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2c,
	0x0a, 0x16, 0x47, 0x65, 0x74, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1b, 0x0a, 0x19,
	0x47, 0x65, 0x74, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x30, 0x0a, 0x1a, 0x47, 0x65, 0x74,
	0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1e, 0x0a, 0x1c, 0x47,
	0x65, 0x74, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x41, 0x0a, 0x1d, 0x47,
	0x65, 0x74, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x12,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x61, 0x75, 0x73, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x2b, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x50, 0x61, 0x75, 0x73, 0x65, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x75, 0x73, 0x65,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x70, 0x61, 0x75, 0x73, 0x65, 0x64, 0x22,
	0x2a, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x50, 0x61, 0x75, 0x73, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x75, 0x73, 0x65, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x70, 0x61, 0x75, 0x73, 0x65, 0x64, 0x22, 0x13, 0x0a, 0x11, 0x53,
	0x65, 0x74, 0x50, 0x61, 0x75, 0x73, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x1d, 0x0a, 0x1b, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x1e, 0x0a, 0x1c, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x18, 0x0a, 0x16, 0x4c, 0x6f, 0x61, 0x64, 0x4e, 0x65, 0x78, 0x74, 0x4d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x31, 0x0a, 0x17, 0x4c, 0x6f, 0x61,
	0x64, 0x4e, 0x65, 0x78, 0x74, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x22, 0x31, 0x0a, 0x12,
	0x4c, 0x6f, 0x61, 0x64, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x15, 0x0a, 0x13, 0x4c, 0x6f, 0x61, 0x64, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x53, 0x74, 0x6f, 0x70, 0x4d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a, 0x13,
	0x53, 0x74, 0x6f, 0x70, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x1f, 0x0a, 0x0b, 0x45, 0x76, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x75, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6c, 0x75, 0x61, 0x22, 0x22, 0x0a, 0x0c, 0x45, 0x76, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x22, 0x14, 0x0a, 0x12, 0x45, 0x78, 0x69, 0x74,
	0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15,
	0x0a, 0x13, 0x45, 0x78, 0x69, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x16, 0x0a, 0x14, 0x49, 0x73, 0x4d, 0x75, 0x6c, 0x74, 0x69,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x39, 0x0a,
	0x15, 0x49, 0x73, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x6d, 0x75, 0x6c,
	0x74, 0x69, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x11, 0x0a, 0x0f, 0x49, 0x73, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2a, 0x0a, 0x10, 0x49,
	0x73, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x52, 0x0a, 0x10, 0x42, 0x61, 0x6e, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x70, 0x65, 0x72,
	0x69, 0x6f, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x2b, 0x0a, 0x11, 0x42,
	0x61, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x22, 0x28, 0x0a, 0x12, 0x55, 0x6e, 0x62, 0x61,
	0x6e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x63,
	0x69, 0x64, 0x22, 0x31, 0x0a, 0x13, 0x55, 0x6e, 0x62, 0x61, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x6e, 0x62,
	0x61, 0x6e, 0x6e, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x75, 0x6e, 0x62,
	0x61, 0x6e, 0x6e, 0x65, 0x64, 0x22, 0x19, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6e, 0x6e,
	0x65, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x47, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x04,
	0x62, 0x61, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64, 0x63, 0x73,
	0x2e, 0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x30, 0x2e, 0x42, 0x61, 0x6e, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x52, 0x04, 0x62, 0x61, 0x6e, 0x73, 0x22, 0xbc, 0x01, 0x0a, 0x0a, 0x42, 0x61,
	0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x63, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x63, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x69, 0x70, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x69, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x5f, 0x66,
	0x72, 0x6f, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x62, 0x61, 0x6e, 0x6e, 0x65,
	0x64, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x21, 0x0a, 0x0c, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x5f,
	0x75, 0x6e, 0x74, 0x69, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x62, 0x61, 0x6e,
	0x6e, 0x65, 0x64, 0x55, 0x6e, 0x74, 0x69, 0x6c, 0x22, 0x24, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x55,
	0x6e, 0x69, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x29,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x29, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x1b, 0x0a, 0x19, 0x47, 0x65,
	0x74, 0x42, 0x61, 0x6c, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x32, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x42, 0x61,
	0x6c, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0xa6, 0x0d, 0x0a, 0x0b,
	0x48, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5b, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x2e,
	0x64, 0x63, 0x73, 0x2e, 0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x4d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x23, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x30, 0x2e,
	0x47, 0x65, 0x74, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x67, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x26,
	0x2e, 0x64, 0x63, 0x73, 0x2e, 0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74,
	0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x68, 0x6f, 0x6f,
	0x6b, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x46,
	0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x70, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x2e, 0x64, 0x63, 0x73,
	0x2e, 0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x68, 0x6f, 0x6f, 0x6b,
	0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x50, 0x61, 0x75, 0x73, 0x65, 0x64,
	0x12, 0x1d, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x30, 0x2e, 0x47,
	0x65, 0x74, 0x50, 0x61, 0x75, 0x73, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1e, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65,
	0x74, 0x50, 0x61, 0x75, 0x73, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x4c, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x50, 0x61, 0x75, 0x73, 0x65, 0x64, 0x12, 0x1d,
	0x2e, 0x64, 0x63, 0x73, 0x2e, 0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x30, 0x2e, 0x53, 0x65, 0x74,
	0x50, 0x61, 0x75, 0x73, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e,
	0x64, 0x63, 0x73, 0x2e, 0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x30, 0x2e, 0x53, 0x65, 0x74, 0x50,
	0x61, 0x75, 0x73, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x52, 0x0a, 0x0b, 0x53, 0x74, 0x6f, 0x70, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1f,
	0x2e, 0x64, 0x63, 0x73, 0x2e, 0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x30, 0x2e, 0x53, 0x74, 0x6f,
	0x70, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x20, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x30, 0x2e, 0x53, 0x74,
	0x6f, 0x70, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x6d, 0x0a, 0x14, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x2e, 0x64, 0x63,
	0x73, 0x2e, 0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x30, 0x2e, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64,
	0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x68, 0x6f, 0x6f, 0x6b,
	0x2e, 0x76, 0x30, 0x2e, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x5e, 0x0a, 0x0f, 0x4c, 0x6f, 0x61, 0x64, 0x4e, 0x65, 0x78, 0x74, 0x4d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x68, 0x6f, 0x6f, 0x6b,
	0x2e, 0x76, 0x30, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x4e, 0x65, 0x78, 0x74, 0x4d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x64, 0x63, 0x73,
	0x2e, 0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x30, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x4e, 0x65, 0x78,
	0x74, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x52, 0x0a, 0x0b, 0x4c, 0x6f, 0x61, 0x64, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x1f, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x30, 0x2e,
	0x4c, 0x6f, 0x61, 0x64, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x20, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x30,
	0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x04, 0x45, 0x76, 0x61, 0x6c, 0x12, 0x18,
	0x2e, 0x64, 0x63, 0x73, 0x2e, 0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x30, 0x2e, 0x45, 0x76, 0x61,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x68,
	0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x30, 0x2e, 0x45, 0x76, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x0b, 0x45, 0x78, 0x69, 0x74, 0x50, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x1f, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x68, 0x6f, 0x6f, 0x6b, 0x2e,
	0x76, 0x30, 0x2e, 0x45, 0x78, 0x69, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x68, 0x6f, 0x6f, 0x6b,
	0x2e, 0x76, 0x30, 0x2e, 0x45, 0x78, 0x69, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x0d, 0x49, 0x73, 0x4d,
	0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x21, 0x2e, 0x64, 0x63, 0x73,
	0x2e, 0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x30, 0x2e, 0x49, 0x73, 0x4d, 0x75, 0x6c, 0x74, 0x69,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e,
	0x64, 0x63, 0x73, 0x2e, 0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x30, 0x2e, 0x49, 0x73, 0x4d, 0x75,
	0x6c, 0x74, 0x69, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x08, 0x49, 0x73, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12,
	0x1c, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x30, 0x2e, 0x49, 0x73,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x64, 0x63, 0x73, 0x2e, 0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x30, 0x2e, 0x49, 0x73, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c,
	0x0a, 0x09, 0x42, 0x61, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x1d, 0x2e, 0x64, 0x63,
	0x73, 0x2e, 0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x30, 0x2e, 0x42, 0x61, 0x6e, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x64, 0x63, 0x73,
	0x2e, 0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x30, 0x2e, 0x42, 0x61, 0x6e, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x0b,
	0x55, 0x6e, 0x62, 0x61, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x1f, 0x2e, 0x64, 0x63,
	0x73, 0x2e, 0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x30, 0x2e, 0x55, 0x6e, 0x62, 0x61, 0x6e, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x64,
	0x63, 0x73, 0x2e, 0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x30, 0x2e, 0x55, 0x6e, 0x62, 0x61, 0x6e,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x61, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x73, 0x12, 0x24, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x68, 0x6f, 0x6f, 0x6b, 0x2e,
	0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x64, 0x63, 0x73,
	0x2e, 0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6e, 0x6e,
	0x65, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x1f, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x30,
	0x2e, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x76,
	0x30, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1f, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x68, 0x6f, 0x6f,
	0x6b, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x68, 0x6f,
	0x6f, 0x6b, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x6c, 0x54, 0x69, 0x6d,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x67, 0x0a, 0x12, 0x47,
	0x65, 0x74, 0x42, 0x61, 0x6c, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x26, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x30, 0x2e,
	0x47, 0x65, 0x74, 0x42, 0x61, 0x6c, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x64, 0x63, 0x73, 0x2e,
	0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6c, 0x6c, 0x69,
	0x73, 0x74, 0x69, 0x63, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x4d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x44, 0x43, 0x53, 0x2d, 0x67, 0x52, 0x50, 0x43, 0x2f, 0x67, 0x6f, 0x2d, 0x62,
	0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x2f, 0x64, 0x63, 0x73, 0x2f, 0x76, 0x30, 0x2f, 0x68,
	0x6f, 0x6f, 0x6b, 0xaa, 0x02, 0x1d, 0x52, 0x75, 0x72, 0x6f, 0x75, 0x6e, 0x69, 0x4a, 0x6f, 0x6e,
	0x65, 0x73, 0x2e, 0x44, 0x63, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x30, 0x2e, 0x48,
	0x6f, 0x6f, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dcs_hook_v0_hook_proto_rawDescOnce sync.Once
	file_dcs_hook_v0_hook_proto_rawDescData = file_dcs_hook_v0_hook_proto_rawDesc
)

func file_dcs_hook_v0_hook_proto_rawDescGZIP() []byte {
	file_dcs_hook_v0_hook_proto_rawDescOnce.Do(func() {
		file_dcs_hook_v0_hook_proto_rawDescData = protoimpl.X.CompressGZIP(file_dcs_hook_v0_hook_proto_rawDescData)
	})
	return file_dcs_hook_v0_hook_proto_rawDescData
}

var file_dcs_hook_v0_hook_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_dcs_hook_v0_hook_proto_goTypes = []interface{}{
	(*GetMissionNameRequest)(nil),         // 0: dcs.hook.v0.GetMissionNameRequest
	(*GetMissionNameResponse)(nil),        // 1: dcs.hook.v0.GetMissionNameResponse
	(*GetMissionFilenameRequest)(nil),     // 2: dcs.hook.v0.GetMissionFilenameRequest
	(*GetMissionFilenameResponse)(nil),    // 3: dcs.hook.v0.GetMissionFilenameResponse
	(*GetMissionDescriptionRequest)(nil),  // 4: dcs.hook.v0.GetMissionDescriptionRequest
	(*GetMissionDescriptionResponse)(nil), // 5: dcs.hook.v0.GetMissionDescriptionResponse
	(*GetPausedRequest)(nil),              // 6: dcs.hook.v0.GetPausedRequest
	(*GetPausedResponse)(nil),             // 7: dcs.hook.v0.GetPausedResponse
	(*SetPausedRequest)(nil),              // 8: dcs.hook.v0.SetPausedRequest
	(*SetPausedResponse)(nil),             // 9: dcs.hook.v0.SetPausedResponse
	(*ReloadCurrentMissionRequest)(nil),   // 10: dcs.hook.v0.ReloadCurrentMissionRequest
	(*ReloadCurrentMissionResponse)(nil),  // 11: dcs.hook.v0.ReloadCurrentMissionResponse
	(*LoadNextMissionRequest)(nil),        // 12: dcs.hook.v0.LoadNextMissionRequest
	(*LoadNextMissionResponse)(nil),       // 13: dcs.hook.v0.LoadNextMissionResponse
	(*LoadMissionRequest)(nil),            // 14: dcs.hook.v0.LoadMissionRequest
	(*LoadMissionResponse)(nil),           // 15: dcs.hook.v0.LoadMissionResponse
	(*StopMissionRequest)(nil),            // 16: dcs.hook.v0.StopMissionRequest
	(*StopMissionResponse)(nil),           // 17: dcs.hook.v0.StopMissionResponse
	(*EvalRequest)(nil),                   // 18: dcs.hook.v0.EvalRequest
	(*EvalResponse)(nil),                  // 19: dcs.hook.v0.EvalResponse
	(*ExitProcessRequest)(nil),            // 20: dcs.hook.v0.ExitProcessRequest
	(*ExitProcessResponse)(nil),           // 21: dcs.hook.v0.ExitProcessResponse
	(*IsMultiplayerRequest)(nil),          // 22: dcs.hook.v0.IsMultiplayerRequest
	(*IsMultiplayerResponse)(nil),         // 23: dcs.hook.v0.IsMultiplayerResponse
	(*IsServerRequest)(nil),               // 24: dcs.hook.v0.IsServerRequest
	(*IsServerResponse)(nil),              // 25: dcs.hook.v0.IsServerResponse
	(*BanPlayerRequest)(nil),              // 26: dcs.hook.v0.BanPlayerRequest
	(*BanPlayerResponse)(nil),             // 27: dcs.hook.v0.BanPlayerResponse
	(*UnbanPlayerRequest)(nil),            // 28: dcs.hook.v0.UnbanPlayerRequest
	(*UnbanPlayerResponse)(nil),           // 29: dcs.hook.v0.UnbanPlayerResponse
	(*GetBannedPlayersRequest)(nil),       // 30: dcs.hook.v0.GetBannedPlayersRequest
	(*GetBannedPlayersResponse)(nil),      // 31: dcs.hook.v0.GetBannedPlayersResponse
	(*BanDetails)(nil),                    // 32: dcs.hook.v0.BanDetails
	(*GetUnitTypeRequest)(nil),            // 33: dcs.hook.v0.GetUnitTypeRequest
	(*GetUnitTypeResponse)(nil),           // 34: dcs.hook.v0.GetUnitTypeResponse
	(*GetRealTimeRequest)(nil),            // 35: dcs.hook.v0.GetRealTimeRequest
	(*GetRealTimeResponse)(nil),           // 36: dcs.hook.v0.GetRealTimeResponse
	(*GetBallisticsCountRequest)(nil),     // 37: dcs.hook.v0.GetBallisticsCountRequest
	(*GetBallisticsCountResponse)(nil),    // 38: dcs.hook.v0.GetBallisticsCountResponse
}
var file_dcs_hook_v0_hook_proto_depIdxs = []int32{
	32, // 0: dcs.hook.v0.GetBannedPlayersResponse.bans:type_name -> dcs.hook.v0.BanDetails
	0,  // 1: dcs.hook.v0.HookService.GetMissionName:input_type -> dcs.hook.v0.GetMissionNameRequest
	2,  // 2: dcs.hook.v0.HookService.GetMissionFilename:input_type -> dcs.hook.v0.GetMissionFilenameRequest
	4,  // 3: dcs.hook.v0.HookService.GetMissionDescription:input_type -> dcs.hook.v0.GetMissionDescriptionRequest
	6,  // 4: dcs.hook.v0.HookService.GetPaused:input_type -> dcs.hook.v0.GetPausedRequest
	8,  // 5: dcs.hook.v0.HookService.SetPaused:input_type -> dcs.hook.v0.SetPausedRequest
	16, // 6: dcs.hook.v0.HookService.StopMission:input_type -> dcs.hook.v0.StopMissionRequest
	10, // 7: dcs.hook.v0.HookService.ReloadCurrentMission:input_type -> dcs.hook.v0.ReloadCurrentMissionRequest
	12, // 8: dcs.hook.v0.HookService.LoadNextMission:input_type -> dcs.hook.v0.LoadNextMissionRequest
	14, // 9: dcs.hook.v0.HookService.LoadMission:input_type -> dcs.hook.v0.LoadMissionRequest
	18, // 10: dcs.hook.v0.HookService.Eval:input_type -> dcs.hook.v0.EvalRequest
	20, // 11: dcs.hook.v0.HookService.ExitProcess:input_type -> dcs.hook.v0.ExitProcessRequest
	22, // 12: dcs.hook.v0.HookService.IsMultiplayer:input_type -> dcs.hook.v0.IsMultiplayerRequest
	24, // 13: dcs.hook.v0.HookService.IsServer:input_type -> dcs.hook.v0.IsServerRequest
	26, // 14: dcs.hook.v0.HookService.BanPlayer:input_type -> dcs.hook.v0.BanPlayerRequest
	28, // 15: dcs.hook.v0.HookService.UnbanPlayer:input_type -> dcs.hook.v0.UnbanPlayerRequest
	30, // 16: dcs.hook.v0.HookService.GetBannedPlayers:input_type -> dcs.hook.v0.GetBannedPlayersRequest
	33, // 17: dcs.hook.v0.HookService.GetUnitType:input_type -> dcs.hook.v0.GetUnitTypeRequest
	35, // 18: dcs.hook.v0.HookService.GetRealTime:input_type -> dcs.hook.v0.GetRealTimeRequest
	37, // 19: dcs.hook.v0.HookService.GetBallisticsCount:input_type -> dcs.hook.v0.GetBallisticsCountRequest
	1,  // 20: dcs.hook.v0.HookService.GetMissionName:output_type -> dcs.hook.v0.GetMissionNameResponse
	3,  // 21: dcs.hook.v0.HookService.GetMissionFilename:output_type -> dcs.hook.v0.GetMissionFilenameResponse
	5,  // 22: dcs.hook.v0.HookService.GetMissionDescription:output_type -> dcs.hook.v0.GetMissionDescriptionResponse
	7,  // 23: dcs.hook.v0.HookService.GetPaused:output_type -> dcs.hook.v0.GetPausedResponse
	9,  // 24: dcs.hook.v0.HookService.SetPaused:output_type -> dcs.hook.v0.SetPausedResponse
	17, // 25: dcs.hook.v0.HookService.StopMission:output_type -> dcs.hook.v0.StopMissionResponse
	11, // 26: dcs.hook.v0.HookService.ReloadCurrentMission:output_type -> dcs.hook.v0.ReloadCurrentMissionResponse
	13, // 27: dcs.hook.v0.HookService.LoadNextMission:output_type -> dcs.hook.v0.LoadNextMissionResponse
	15, // 28: dcs.hook.v0.HookService.LoadMission:output_type -> dcs.hook.v0.LoadMissionResponse
	19, // 29: dcs.hook.v0.HookService.Eval:output_type -> dcs.hook.v0.EvalResponse
	21, // 30: dcs.hook.v0.HookService.ExitProcess:output_type -> dcs.hook.v0.ExitProcessResponse
	23, // 31: dcs.hook.v0.HookService.IsMultiplayer:output_type -> dcs.hook.v0.IsMultiplayerResponse
	25, // 32: dcs.hook.v0.HookService.IsServer:output_type -> dcs.hook.v0.IsServerResponse
	27, // 33: dcs.hook.v0.HookService.BanPlayer:output_type -> dcs.hook.v0.BanPlayerResponse
	29, // 34: dcs.hook.v0.HookService.UnbanPlayer:output_type -> dcs.hook.v0.UnbanPlayerResponse
	31, // 35: dcs.hook.v0.HookService.GetBannedPlayers:output_type -> dcs.hook.v0.GetBannedPlayersResponse
	34, // 36: dcs.hook.v0.HookService.GetUnitType:output_type -> dcs.hook.v0.GetUnitTypeResponse
	36, // 37: dcs.hook.v0.HookService.GetRealTime:output_type -> dcs.hook.v0.GetRealTimeResponse
	38, // 38: dcs.hook.v0.HookService.GetBallisticsCount:output_type -> dcs.hook.v0.GetBallisticsCountResponse
	20, // [20:39] is the sub-list for method output_type
	1,  // [1:20] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_dcs_hook_v0_hook_proto_init() }
func file_dcs_hook_v0_hook_proto_init() {
	if File_dcs_hook_v0_hook_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dcs_hook_v0_hook_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMissionNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMissionNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMissionFilenameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMissionFilenameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMissionDescriptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMissionDescriptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPausedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPausedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetPausedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetPausedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReloadCurrentMissionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReloadCurrentMissionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadNextMissionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadNextMissionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadMissionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadMissionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopMissionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopMissionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExitProcessRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExitProcessResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsMultiplayerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsMultiplayerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsServerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BanPlayerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BanPlayerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnbanPlayerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnbanPlayerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBannedPlayersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBannedPlayersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BanDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUnitTypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[34].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUnitTypeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[35].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRealTimeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[36].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRealTimeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[37].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBallisticsCountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_hook_v0_hook_proto_msgTypes[38].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBallisticsCountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dcs_hook_v0_hook_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dcs_hook_v0_hook_proto_goTypes,
		DependencyIndexes: file_dcs_hook_v0_hook_proto_depIdxs,
		MessageInfos:      file_dcs_hook_v0_hook_proto_msgTypes,
	}.Build()
	File_dcs_hook_v0_hook_proto = out.File
	file_dcs_hook_v0_hook_proto_rawDesc = nil
	file_dcs_hook_v0_hook_proto_goTypes = nil
	file_dcs_hook_v0_hook_proto_depIdxs = nil
}
