// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.12
// source: dcs/unit/v0/unit.proto

package unit

import (
	common "github.com/DCS-gRPC/go-bindings/dcs/v0/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRadarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetRadarRequest) Reset() {
	*x = GetRadarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_unit_v0_unit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRadarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRadarRequest) ProtoMessage() {}

func (x *GetRadarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_unit_v0_unit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRadarRequest.ProtoReflect.Descriptor instead.
func (*GetRadarRequest) Descriptor() ([]byte, []int) {
	return file_dcs_unit_v0_unit_proto_rawDescGZIP(), []int{0}
}

func (x *GetRadarRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetRadarResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Active bool           `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	Target *common.Target `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *GetRadarResponse) Reset() {
	*x = GetRadarResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_unit_v0_unit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRadarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRadarResponse) ProtoMessage() {}

func (x *GetRadarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_unit_v0_unit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRadarResponse.ProtoReflect.Descriptor instead.
func (*GetRadarResponse) Descriptor() ([]byte, []int) {
	return file_dcs_unit_v0_unit_proto_rawDescGZIP(), []int{1}
}

func (x *GetRadarResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *GetRadarResponse) GetTarget() *common.Target {
	if x != nil {
		return x.Target
	}
	return nil
}

type GetPositionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetPositionRequest) Reset() {
	*x = GetPositionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_unit_v0_unit_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionRequest) ProtoMessage() {}

func (x *GetPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_unit_v0_unit_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionRequest.ProtoReflect.Descriptor instead.
func (*GetPositionRequest) Descriptor() ([]byte, []int) {
	return file_dcs_unit_v0_unit_proto_rawDescGZIP(), []int{2}
}

func (x *GetPositionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetPositionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position *common.Position `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *GetPositionResponse) Reset() {
	*x = GetPositionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_unit_v0_unit_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionResponse) ProtoMessage() {}

func (x *GetPositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_unit_v0_unit_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionResponse.ProtoReflect.Descriptor instead.
func (*GetPositionResponse) Descriptor() ([]byte, []int) {
	return file_dcs_unit_v0_unit_proto_rawDescGZIP(), []int{3}
}

func (x *GetPositionResponse) GetPosition() *common.Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type GetDrawArgumentValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Argument uint32 `protobuf:"varint,2,opt,name=argument,proto3" json:"argument,omitempty"`
}

func (x *GetDrawArgumentValueRequest) Reset() {
	*x = GetDrawArgumentValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_unit_v0_unit_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDrawArgumentValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDrawArgumentValueRequest) ProtoMessage() {}

func (x *GetDrawArgumentValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_unit_v0_unit_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDrawArgumentValueRequest.ProtoReflect.Descriptor instead.
func (*GetDrawArgumentValueRequest) Descriptor() ([]byte, []int) {
	return file_dcs_unit_v0_unit_proto_rawDescGZIP(), []int{4}
}

func (x *GetDrawArgumentValueRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetDrawArgumentValueRequest) GetArgument() uint32 {
	if x != nil {
		return x.Argument
	}
	return 0
}

type GetDrawArgumentValueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value float64 `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetDrawArgumentValueResponse) Reset() {
	*x = GetDrawArgumentValueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_unit_v0_unit_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDrawArgumentValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDrawArgumentValueResponse) ProtoMessage() {}

func (x *GetDrawArgumentValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_unit_v0_unit_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDrawArgumentValueResponse.ProtoReflect.Descriptor instead.
func (*GetDrawArgumentValueResponse) Descriptor() ([]byte, []int) {
	return file_dcs_unit_v0_unit_proto_rawDescGZIP(), []int{5}
}

func (x *GetDrawArgumentValueResponse) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type GetTransformRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetTransformRequest) Reset() {
	*x = GetTransformRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_unit_v0_unit_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTransformRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransformRequest) ProtoMessage() {}

func (x *GetTransformRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_unit_v0_unit_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransformRequest.ProtoReflect.Descriptor instead.
func (*GetTransformRequest) Descriptor() ([]byte, []int) {
	return file_dcs_unit_v0_unit_proto_rawDescGZIP(), []int{6}
}

func (x *GetTransformRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetTransformResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Time in seconds since the scenario started.
	Time float64 `protobuf:"fixed64,1,opt,name=time,proto3" json:"time,omitempty"`
	// The position of the unit
	Position *common.Position `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	// The orientation of the unit in both 2D and 3D space
	Orientation *common.Orientation `protobuf:"bytes,3,opt,name=orientation,proto3" json:"orientation,omitempty"`
	// The velocity of the unit in both 2D and 3D space
	Velocity *common.Velocity `protobuf:"bytes,4,opt,name=velocity,proto3" json:"velocity,omitempty"`
}

func (x *GetTransformResponse) Reset() {
	*x = GetTransformResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_unit_v0_unit_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTransformResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransformResponse) ProtoMessage() {}

func (x *GetTransformResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_unit_v0_unit_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransformResponse.ProtoReflect.Descriptor instead.
func (*GetTransformResponse) Descriptor() ([]byte, []int) {
	return file_dcs_unit_v0_unit_proto_rawDescGZIP(), []int{7}
}

func (x *GetTransformResponse) GetTime() float64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *GetTransformResponse) GetPosition() *common.Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *GetTransformResponse) GetOrientation() *common.Orientation {
	if x != nil {
		return x.Orientation
	}
	return nil
}

func (x *GetTransformResponse) GetVelocity() *common.Velocity {
	if x != nil {
		return x.Velocity
	}
	return nil
}

type GetPlayerNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetPlayerNameRequest) Reset() {
	*x = GetPlayerNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_unit_v0_unit_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlayerNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerNameRequest) ProtoMessage() {}

func (x *GetPlayerNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_unit_v0_unit_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerNameRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerNameRequest) Descriptor() ([]byte, []int) {
	return file_dcs_unit_v0_unit_proto_rawDescGZIP(), []int{8}
}

func (x *GetPlayerNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetPlayerNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerName *string `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3,oneof" json:"player_name,omitempty"`
}

func (x *GetPlayerNameResponse) Reset() {
	*x = GetPlayerNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_unit_v0_unit_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlayerNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerNameResponse) ProtoMessage() {}

func (x *GetPlayerNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_unit_v0_unit_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerNameResponse.ProtoReflect.Descriptor instead.
func (*GetPlayerNameResponse) Descriptor() ([]byte, []int) {
	return file_dcs_unit_v0_unit_proto_rawDescGZIP(), []int{9}
}

func (x *GetPlayerNameResponse) GetPlayerName() string {
	if x != nil && x.PlayerName != nil {
		return *x.PlayerName
	}
	return ""
}

type GetDescriptorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetDescriptorRequest) Reset() {
	*x = GetDescriptorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_unit_v0_unit_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDescriptorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDescriptorRequest) ProtoMessage() {}

func (x *GetDescriptorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_unit_v0_unit_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDescriptorRequest.ProtoReflect.Descriptor instead.
func (*GetDescriptorRequest) Descriptor() ([]byte, []int) {
	return file_dcs_unit_v0_unit_proto_rawDescGZIP(), []int{10}
}

func (x *GetDescriptorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// TODO fill these in as and when we need em
type GetDescriptorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Attributes []string `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty"`
}

func (x *GetDescriptorResponse) Reset() {
	*x = GetDescriptorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_unit_v0_unit_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDescriptorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDescriptorResponse) ProtoMessage() {}

func (x *GetDescriptorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_unit_v0_unit_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDescriptorResponse.ProtoReflect.Descriptor instead.
func (*GetDescriptorResponse) Descriptor() ([]byte, []int) {
	return file_dcs_unit_v0_unit_proto_rawDescGZIP(), []int{11}
}

func (x *GetDescriptorResponse) GetAttributes() []string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type SetEmissionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Emitting bool   `protobuf:"varint,2,opt,name=emitting,proto3" json:"emitting,omitempty"`
}

func (x *SetEmissionRequest) Reset() {
	*x = SetEmissionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_unit_v0_unit_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetEmissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEmissionRequest) ProtoMessage() {}

func (x *SetEmissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_unit_v0_unit_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEmissionRequest.ProtoReflect.Descriptor instead.
func (*SetEmissionRequest) Descriptor() ([]byte, []int) {
	return file_dcs_unit_v0_unit_proto_rawDescGZIP(), []int{12}
}

func (x *SetEmissionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetEmissionRequest) GetEmitting() bool {
	if x != nil {
		return x.Emitting
	}
	return false
}

type SetEmissionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetEmissionResponse) Reset() {
	*x = SetEmissionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_unit_v0_unit_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetEmissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEmissionResponse) ProtoMessage() {}

func (x *SetEmissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_unit_v0_unit_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEmissionResponse.ProtoReflect.Descriptor instead.
func (*SetEmissionResponse) Descriptor() ([]byte, []int) {
	return file_dcs_unit_v0_unit_proto_rawDescGZIP(), []int{13}
}

type GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_unit_v0_unit_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_unit_v0_unit_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_dcs_unit_v0_unit_proto_rawDescGZIP(), []int{14}
}

func (x *GetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Unit *common.Unit `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_unit_v0_unit_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_unit_v0_unit_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_dcs_unit_v0_unit_proto_rawDescGZIP(), []int{15}
}

func (x *GetResponse) GetUnit() *common.Unit {
	if x != nil {
		return x.Unit
	}
	return nil
}

type DestroyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DestroyRequest) Reset() {
	*x = DestroyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_unit_v0_unit_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyRequest) ProtoMessage() {}

func (x *DestroyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_unit_v0_unit_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyRequest.ProtoReflect.Descriptor instead.
func (*DestroyRequest) Descriptor() ([]byte, []int) {
	return file_dcs_unit_v0_unit_proto_rawDescGZIP(), []int{16}
}

func (x *DestroyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DestroyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DestroyResponse) Reset() {
	*x = DestroyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_unit_v0_unit_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyResponse) ProtoMessage() {}

func (x *DestroyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_unit_v0_unit_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyResponse.ProtoReflect.Descriptor instead.
func (*DestroyResponse) Descriptor() ([]byte, []int) {
	return file_dcs_unit_v0_unit_proto_rawDescGZIP(), []int{17}
}

var File_dcs_unit_v0_unit_proto protoreflect.FileDescriptor

var file_dcs_unit_v0_unit_proto_rawDesc = []byte{
	0x0a, 0x16, 0x64, 0x63, 0x73, 0x2f, 0x75, 0x6e, 0x69, 0x74, 0x2f, 0x76, 0x30, 0x2f, 0x75, 0x6e,
	0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x64, 0x63, 0x73, 0x2e, 0x75, 0x6e,
	0x69, 0x74, 0x2e, 0x76, 0x30, 0x1a, 0x1a, 0x64, 0x63, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2f, 0x76, 0x30, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x25, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x52, 0x61, 0x64, 0x61, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x59, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x52,
	0x61, 0x64, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x06, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x22, 0x28, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x4a, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4d, 0x0a, 0x1b, 0x47, 0x65, 0x74,
	0x44, 0x72, 0x61, 0x77, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x34, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x44,
	0x72, 0x61, 0x77, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x29,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xd2, 0x01, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x33, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3c, 0x0a, 0x0b, 0x6f,
	0x72, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x30,
	0x2e, 0x4f, 0x72, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x6f, 0x72,
	0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x33, 0x0a, 0x08, 0x76, 0x65, 0x6c,
	0x6f, 0x63, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64, 0x63,
	0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x56, 0x65, 0x6c, 0x6f,
	0x63, 0x69, 0x74, 0x79, 0x52, 0x08, 0x76, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x22, 0x2a,
	0x0a, 0x14, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x4d, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2a, 0x0a, 0x14, 0x47, 0x65, 0x74,
	0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x37, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x22, 0x44,
	0x0a, 0x12, 0x53, 0x65, 0x74, 0x45, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6d, 0x69, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x65, 0x6d, 0x69, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x22, 0x15, 0x0a, 0x13, 0x53, 0x65, 0x74, 0x45, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x20, 0x0a, 0x0a, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x36, 0x0a,
	0x0b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x04,
	0x75, 0x6e, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x64, 0x63, 0x73,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x55, 0x6e, 0x69, 0x74, 0x52,
	0x04, 0x75, 0x6e, 0x69, 0x74, 0x22, 0x24, 0x0a, 0x0e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x11, 0x0a, 0x0f, 0x44,
	0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xfe,
	0x05, 0x0a, 0x0b, 0x55, 0x6e, 0x69, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x49,
	0x0a, 0x08, 0x47, 0x65, 0x74, 0x52, 0x61, 0x64, 0x61, 0x72, 0x12, 0x1c, 0x2e, 0x64, 0x63, 0x73,
	0x2e, 0x75, 0x6e, 0x69, 0x74, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x64, 0x61,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x75,
	0x6e, 0x69, 0x74, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x64, 0x61, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x0b, 0x47, 0x65, 0x74,
	0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x75,
	0x6e, 0x69, 0x74, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x64, 0x63, 0x73, 0x2e,
	0x75, 0x6e, 0x69, 0x74, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21,
	0x2e, 0x64, 0x63, 0x73, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x22, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x2e, 0x76, 0x30, 0x2e,
	0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x12, 0x21, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x75,
	0x6e, 0x69, 0x74, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x64, 0x63,
	0x73, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x52, 0x0a, 0x0b, 0x53, 0x65, 0x74, 0x45, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x1f, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x2e, 0x76, 0x30, 0x2e, 0x53,
	0x65, 0x74, 0x45, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x20, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x2e, 0x76, 0x30, 0x2e,
	0x53, 0x65, 0x74, 0x45, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x17, 0x2e, 0x64,
	0x63, 0x73, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x75, 0x6e, 0x69, 0x74,
	0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x55, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72,
	0x6d, 0x12, 0x20, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x2e, 0x76, 0x30, 0x2e,
	0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x2e, 0x76,
	0x30, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x07, 0x44, 0x65, 0x73, 0x74,
	0x72, 0x6f, 0x79, 0x12, 0x1b, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x2e, 0x76,
	0x30, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x2e, 0x76, 0x30, 0x2e, 0x44,
	0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x6d, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x44, 0x72, 0x61, 0x77, 0x41, 0x72, 0x67, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x28, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x75,
	0x6e, 0x69, 0x74, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x72, 0x61, 0x77, 0x41, 0x72,
	0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x29, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x2e, 0x76, 0x30,
	0x2e, 0x47, 0x65, 0x74, 0x44, 0x72, 0x61, 0x77, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x4d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x44, 0x43,
	0x53, 0x2d, 0x67, 0x52, 0x50, 0x43, 0x2f, 0x67, 0x6f, 0x2d, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x73, 0x2f, 0x64, 0x63, 0x73, 0x2f, 0x76, 0x30, 0x2f, 0x75, 0x6e, 0x69, 0x74, 0xaa, 0x02,
	0x1d, 0x52, 0x75, 0x72, 0x6f, 0x75, 0x6e, 0x69, 0x4a, 0x6f, 0x6e, 0x65, 0x73, 0x2e, 0x44, 0x63,
	0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x30, 0x2e, 0x55, 0x6e, 0x69, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dcs_unit_v0_unit_proto_rawDescOnce sync.Once
	file_dcs_unit_v0_unit_proto_rawDescData = file_dcs_unit_v0_unit_proto_rawDesc
)

func file_dcs_unit_v0_unit_proto_rawDescGZIP() []byte {
	file_dcs_unit_v0_unit_proto_rawDescOnce.Do(func() {
		file_dcs_unit_v0_unit_proto_rawDescData = protoimpl.X.CompressGZIP(file_dcs_unit_v0_unit_proto_rawDescData)
	})
	return file_dcs_unit_v0_unit_proto_rawDescData
}

var file_dcs_unit_v0_unit_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_dcs_unit_v0_unit_proto_goTypes = []interface{}{
	(*GetRadarRequest)(nil),              // 0: dcs.unit.v0.GetRadarRequest
	(*GetRadarResponse)(nil),             // 1: dcs.unit.v0.GetRadarResponse
	(*GetPositionRequest)(nil),           // 2: dcs.unit.v0.GetPositionRequest
	(*GetPositionResponse)(nil),          // 3: dcs.unit.v0.GetPositionResponse
	(*GetDrawArgumentValueRequest)(nil),  // 4: dcs.unit.v0.GetDrawArgumentValueRequest
	(*GetDrawArgumentValueResponse)(nil), // 5: dcs.unit.v0.GetDrawArgumentValueResponse
	(*GetTransformRequest)(nil),          // 6: dcs.unit.v0.GetTransformRequest
	(*GetTransformResponse)(nil),         // 7: dcs.unit.v0.GetTransformResponse
	(*GetPlayerNameRequest)(nil),         // 8: dcs.unit.v0.GetPlayerNameRequest
	(*GetPlayerNameResponse)(nil),        // 9: dcs.unit.v0.GetPlayerNameResponse
	(*GetDescriptorRequest)(nil),         // 10: dcs.unit.v0.GetDescriptorRequest
	(*GetDescriptorResponse)(nil),        // 11: dcs.unit.v0.GetDescriptorResponse
	(*SetEmissionRequest)(nil),           // 12: dcs.unit.v0.SetEmissionRequest
	(*SetEmissionResponse)(nil),          // 13: dcs.unit.v0.SetEmissionResponse
	(*GetRequest)(nil),                   // 14: dcs.unit.v0.GetRequest
	(*GetResponse)(nil),                  // 15: dcs.unit.v0.GetResponse
	(*DestroyRequest)(nil),               // 16: dcs.unit.v0.DestroyRequest
	(*DestroyResponse)(nil),              // 17: dcs.unit.v0.DestroyResponse
	(*common.Target)(nil),                // 18: dcs.common.v0.Target
	(*common.Position)(nil),              // 19: dcs.common.v0.Position
	(*common.Orientation)(nil),           // 20: dcs.common.v0.Orientation
	(*common.Velocity)(nil),              // 21: dcs.common.v0.Velocity
	(*common.Unit)(nil),                  // 22: dcs.common.v0.Unit
}
var file_dcs_unit_v0_unit_proto_depIdxs = []int32{
	18, // 0: dcs.unit.v0.GetRadarResponse.target:type_name -> dcs.common.v0.Target
	19, // 1: dcs.unit.v0.GetPositionResponse.position:type_name -> dcs.common.v0.Position
	19, // 2: dcs.unit.v0.GetTransformResponse.position:type_name -> dcs.common.v0.Position
	20, // 3: dcs.unit.v0.GetTransformResponse.orientation:type_name -> dcs.common.v0.Orientation
	21, // 4: dcs.unit.v0.GetTransformResponse.velocity:type_name -> dcs.common.v0.Velocity
	22, // 5: dcs.unit.v0.GetResponse.unit:type_name -> dcs.common.v0.Unit
	0,  // 6: dcs.unit.v0.UnitService.GetRadar:input_type -> dcs.unit.v0.GetRadarRequest
	2,  // 7: dcs.unit.v0.UnitService.GetPosition:input_type -> dcs.unit.v0.GetPositionRequest
	8,  // 8: dcs.unit.v0.UnitService.GetPlayerName:input_type -> dcs.unit.v0.GetPlayerNameRequest
	10, // 9: dcs.unit.v0.UnitService.GetDescriptor:input_type -> dcs.unit.v0.GetDescriptorRequest
	12, // 10: dcs.unit.v0.UnitService.SetEmission:input_type -> dcs.unit.v0.SetEmissionRequest
	14, // 11: dcs.unit.v0.UnitService.Get:input_type -> dcs.unit.v0.GetRequest
	6,  // 12: dcs.unit.v0.UnitService.GetTransform:input_type -> dcs.unit.v0.GetTransformRequest
	16, // 13: dcs.unit.v0.UnitService.Destroy:input_type -> dcs.unit.v0.DestroyRequest
	4,  // 14: dcs.unit.v0.UnitService.GetDrawArgumentValue:input_type -> dcs.unit.v0.GetDrawArgumentValueRequest
	1,  // 15: dcs.unit.v0.UnitService.GetRadar:output_type -> dcs.unit.v0.GetRadarResponse
	3,  // 16: dcs.unit.v0.UnitService.GetPosition:output_type -> dcs.unit.v0.GetPositionResponse
	9,  // 17: dcs.unit.v0.UnitService.GetPlayerName:output_type -> dcs.unit.v0.GetPlayerNameResponse
	11, // 18: dcs.unit.v0.UnitService.GetDescriptor:output_type -> dcs.unit.v0.GetDescriptorResponse
	13, // 19: dcs.unit.v0.UnitService.SetEmission:output_type -> dcs.unit.v0.SetEmissionResponse
	15, // 20: dcs.unit.v0.UnitService.Get:output_type -> dcs.unit.v0.GetResponse
	7,  // 21: dcs.unit.v0.UnitService.GetTransform:output_type -> dcs.unit.v0.GetTransformResponse
	17, // 22: dcs.unit.v0.UnitService.Destroy:output_type -> dcs.unit.v0.DestroyResponse
	5,  // 23: dcs.unit.v0.UnitService.GetDrawArgumentValue:output_type -> dcs.unit.v0.GetDrawArgumentValueResponse
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_dcs_unit_v0_unit_proto_init() }
func file_dcs_unit_v0_unit_proto_init() {
	if File_dcs_unit_v0_unit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dcs_unit_v0_unit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRadarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_unit_v0_unit_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRadarResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_unit_v0_unit_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPositionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_unit_v0_unit_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPositionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_unit_v0_unit_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDrawArgumentValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_unit_v0_unit_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDrawArgumentValueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_unit_v0_unit_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTransformRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_unit_v0_unit_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTransformResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_unit_v0_unit_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlayerNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_unit_v0_unit_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlayerNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_unit_v0_unit_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDescriptorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_unit_v0_unit_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDescriptorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_unit_v0_unit_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetEmissionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_unit_v0_unit_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetEmissionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_unit_v0_unit_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_unit_v0_unit_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_unit_v0_unit_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_unit_v0_unit_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_dcs_unit_v0_unit_proto_msgTypes[9].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dcs_unit_v0_unit_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dcs_unit_v0_unit_proto_goTypes,
		DependencyIndexes: file_dcs_unit_v0_unit_proto_depIdxs,
		MessageInfos:      file_dcs_unit_v0_unit_proto_msgTypes,
	}.Build()
	File_dcs_unit_v0_unit_proto = out.File
	file_dcs_unit_v0_unit_proto_rawDesc = nil
	file_dcs_unit_v0_unit_proto_goTypes = nil
	file_dcs_unit_v0_unit_proto_depIdxs = nil
}
