// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: dcs/controller/v0/controller.proto

package controller

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ControllerServiceClient is the client API for ControllerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControllerServiceClient interface {
	// https://wiki.hoggitworld.com/view/DCS_option_alarmState
	SetAlarmState(ctx context.Context, in *SetAlarmStateRequest, opts ...grpc.CallOption) (*SetAlarmStateResponse, error)
	// https://wiki.hoggitworld.com/view/DCS_func_getDetectedTargets
	GetDetectedTargets(ctx context.Context, in *GetDetectedTargetsRequest, opts ...grpc.CallOption) (*GetDetectedTargetsResponse, error)
}

type controllerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControllerServiceClient(cc grpc.ClientConnInterface) ControllerServiceClient {
	return &controllerServiceClient{cc}
}

func (c *controllerServiceClient) SetAlarmState(ctx context.Context, in *SetAlarmStateRequest, opts ...grpc.CallOption) (*SetAlarmStateResponse, error) {
	out := new(SetAlarmStateResponse)
	err := c.cc.Invoke(ctx, "/dcs.controller.v0.ControllerService/SetAlarmState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) GetDetectedTargets(ctx context.Context, in *GetDetectedTargetsRequest, opts ...grpc.CallOption) (*GetDetectedTargetsResponse, error) {
	out := new(GetDetectedTargetsResponse)
	err := c.cc.Invoke(ctx, "/dcs.controller.v0.ControllerService/GetDetectedTargets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerServiceServer is the server API for ControllerService service.
// All implementations must embed UnimplementedControllerServiceServer
// for forward compatibility
type ControllerServiceServer interface {
	// https://wiki.hoggitworld.com/view/DCS_option_alarmState
	SetAlarmState(context.Context, *SetAlarmStateRequest) (*SetAlarmStateResponse, error)
	// https://wiki.hoggitworld.com/view/DCS_func_getDetectedTargets
	GetDetectedTargets(context.Context, *GetDetectedTargetsRequest) (*GetDetectedTargetsResponse, error)
	mustEmbedUnimplementedControllerServiceServer()
}

// UnimplementedControllerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedControllerServiceServer struct {
}

func (UnimplementedControllerServiceServer) SetAlarmState(context.Context, *SetAlarmStateRequest) (*SetAlarmStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAlarmState not implemented")
}
func (UnimplementedControllerServiceServer) GetDetectedTargets(context.Context, *GetDetectedTargetsRequest) (*GetDetectedTargetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDetectedTargets not implemented")
}
func (UnimplementedControllerServiceServer) mustEmbedUnimplementedControllerServiceServer() {}

// UnsafeControllerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControllerServiceServer will
// result in compilation errors.
type UnsafeControllerServiceServer interface {
	mustEmbedUnimplementedControllerServiceServer()
}

func RegisterControllerServiceServer(s grpc.ServiceRegistrar, srv ControllerServiceServer) {
	s.RegisterService(&ControllerService_ServiceDesc, srv)
}

func _ControllerService_SetAlarmState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAlarmStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).SetAlarmState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dcs.controller.v0.ControllerService/SetAlarmState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).SetAlarmState(ctx, req.(*SetAlarmStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_GetDetectedTargets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDetectedTargetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).GetDetectedTargets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dcs.controller.v0.ControllerService/GetDetectedTargets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).GetDetectedTargets(ctx, req.(*GetDetectedTargetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControllerService_ServiceDesc is the grpc.ServiceDesc for ControllerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControllerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dcs.controller.v0.ControllerService",
	HandlerType: (*ControllerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetAlarmState",
			Handler:    _ControllerService_SetAlarmState_Handler,
		},
		{
			MethodName: "GetDetectedTargets",
			Handler:    _ControllerService_GetDetectedTargets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dcs/controller/v0/controller.proto",
}
