// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.12
// source: dcs/coalition/v0/coalition.proto

package coalition

import (
	common "github.com/DCS-gRPC/go-bindings/dcs/v0/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddGroupRequest_Skill int32

const (
	// protolint:disable:next ENUM_FIELD_NAMES_ZERO_VALUE_END_WITH
	AddGroupRequest_SKILL_RANDOM    AddGroupRequest_Skill = 0
	AddGroupRequest_SKILL_AVERAGE   AddGroupRequest_Skill = 1
	AddGroupRequest_SKILL_GOOD      AddGroupRequest_Skill = 2
	AddGroupRequest_SKILL_HIGH      AddGroupRequest_Skill = 3
	AddGroupRequest_SKILL_EXCELLENT AddGroupRequest_Skill = 4
	AddGroupRequest_SKILL_PLAYER    AddGroupRequest_Skill = 5
)

// Enum value maps for AddGroupRequest_Skill.
var (
	AddGroupRequest_Skill_name = map[int32]string{
		0: "SKILL_RANDOM",
		1: "SKILL_AVERAGE",
		2: "SKILL_GOOD",
		3: "SKILL_HIGH",
		4: "SKILL_EXCELLENT",
		5: "SKILL_PLAYER",
	}
	AddGroupRequest_Skill_value = map[string]int32{
		"SKILL_RANDOM":    0,
		"SKILL_AVERAGE":   1,
		"SKILL_GOOD":      2,
		"SKILL_HIGH":      3,
		"SKILL_EXCELLENT": 4,
		"SKILL_PLAYER":    5,
	}
)

func (x AddGroupRequest_Skill) Enum() *AddGroupRequest_Skill {
	p := new(AddGroupRequest_Skill)
	*p = x
	return p
}

func (x AddGroupRequest_Skill) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AddGroupRequest_Skill) Descriptor() protoreflect.EnumDescriptor {
	return file_dcs_coalition_v0_coalition_proto_enumTypes[0].Descriptor()
}

func (AddGroupRequest_Skill) Type() protoreflect.EnumType {
	return &file_dcs_coalition_v0_coalition_proto_enumTypes[0]
}

func (x AddGroupRequest_Skill) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AddGroupRequest_Skill.Descriptor instead.
func (AddGroupRequest_Skill) EnumDescriptor() ([]byte, []int) {
	return file_dcs_coalition_v0_coalition_proto_rawDescGZIP(), []int{0, 0}
}

type AddGroupRequest_Point_AltitudeType int32

const (
	AddGroupRequest_Point_ALTITUDE_TYPE_UNSPECIFIED AddGroupRequest_Point_AltitudeType = 0
	AddGroupRequest_Point_ALTITUDE_TYPE_BAROMETRIC  AddGroupRequest_Point_AltitudeType = 1
	AddGroupRequest_Point_ALTITUDE_TYPE_RADIO       AddGroupRequest_Point_AltitudeType = 2
)

// Enum value maps for AddGroupRequest_Point_AltitudeType.
var (
	AddGroupRequest_Point_AltitudeType_name = map[int32]string{
		0: "ALTITUDE_TYPE_UNSPECIFIED",
		1: "ALTITUDE_TYPE_BAROMETRIC",
		2: "ALTITUDE_TYPE_RADIO",
	}
	AddGroupRequest_Point_AltitudeType_value = map[string]int32{
		"ALTITUDE_TYPE_UNSPECIFIED": 0,
		"ALTITUDE_TYPE_BAROMETRIC":  1,
		"ALTITUDE_TYPE_RADIO":       2,
	}
)

func (x AddGroupRequest_Point_AltitudeType) Enum() *AddGroupRequest_Point_AltitudeType {
	p := new(AddGroupRequest_Point_AltitudeType)
	*p = x
	return p
}

func (x AddGroupRequest_Point_AltitudeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AddGroupRequest_Point_AltitudeType) Descriptor() protoreflect.EnumDescriptor {
	return file_dcs_coalition_v0_coalition_proto_enumTypes[1].Descriptor()
}

func (AddGroupRequest_Point_AltitudeType) Type() protoreflect.EnumType {
	return &file_dcs_coalition_v0_coalition_proto_enumTypes[1]
}

func (x AddGroupRequest_Point_AltitudeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AddGroupRequest_Point_AltitudeType.Descriptor instead.
func (AddGroupRequest_Point_AltitudeType) EnumDescriptor() ([]byte, []int) {
	return file_dcs_coalition_v0_coalition_proto_rawDescGZIP(), []int{0, 8, 0}
}

type AddGroupRequest_Point_PointType int32

const (
	// protolint:disable:next ENUM_FIELD_NAMES_ZERO_VALUE_END_WITH
	AddGroupRequest_Point_POINT_TYPE_RANDOM              AddGroupRequest_Point_PointType = 0
	AddGroupRequest_Point_POINT_TYPE_TAKEOFF             AddGroupRequest_Point_PointType = 1
	AddGroupRequest_Point_POINT_TYPE_TAKEOFF_PARKING     AddGroupRequest_Point_PointType = 2
	AddGroupRequest_Point_POINT_TYPE_TURNING_POINT       AddGroupRequest_Point_PointType = 3
	AddGroupRequest_Point_POINT_TYPE_TAKEOFF_PARKING_HOT AddGroupRequest_Point_PointType = 4
	AddGroupRequest_Point_POINT_TYPE_LAND                AddGroupRequest_Point_PointType = 5
)

// Enum value maps for AddGroupRequest_Point_PointType.
var (
	AddGroupRequest_Point_PointType_name = map[int32]string{
		0: "POINT_TYPE_RANDOM",
		1: "POINT_TYPE_TAKEOFF",
		2: "POINT_TYPE_TAKEOFF_PARKING",
		3: "POINT_TYPE_TURNING_POINT",
		4: "POINT_TYPE_TAKEOFF_PARKING_HOT",
		5: "POINT_TYPE_LAND",
	}
	AddGroupRequest_Point_PointType_value = map[string]int32{
		"POINT_TYPE_RANDOM":              0,
		"POINT_TYPE_TAKEOFF":             1,
		"POINT_TYPE_TAKEOFF_PARKING":     2,
		"POINT_TYPE_TURNING_POINT":       3,
		"POINT_TYPE_TAKEOFF_PARKING_HOT": 4,
		"POINT_TYPE_LAND":                5,
	}
)

func (x AddGroupRequest_Point_PointType) Enum() *AddGroupRequest_Point_PointType {
	p := new(AddGroupRequest_Point_PointType)
	*p = x
	return p
}

func (x AddGroupRequest_Point_PointType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AddGroupRequest_Point_PointType) Descriptor() protoreflect.EnumDescriptor {
	return file_dcs_coalition_v0_coalition_proto_enumTypes[2].Descriptor()
}

func (AddGroupRequest_Point_PointType) Type() protoreflect.EnumType {
	return &file_dcs_coalition_v0_coalition_proto_enumTypes[2]
}

func (x AddGroupRequest_Point_PointType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AddGroupRequest_Point_PointType.Descriptor instead.
func (AddGroupRequest_Point_PointType) EnumDescriptor() ([]byte, []int) {
	return file_dcs_coalition_v0_coalition_proto_rawDescGZIP(), []int{0, 8, 1}
}

type AddGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The coalition is determined by the provided Country
	// and the coalition setup of the mission
	Country       common.Country       `protobuf:"varint,2,opt,name=country,proto3,enum=dcs.common.v0.Country" json:"country,omitempty"`
	GroupCategory common.GroupCategory `protobuf:"varint,3,opt,name=group_category,json=groupCategory,proto3,enum=dcs.common.v0.GroupCategory" json:"group_category,omitempty"`
	// Types that are assignable to Template:
	//
	//	*AddGroupRequest_GroundTemplate
	//	*AddGroupRequest_ShipTemplate
	//	*AddGroupRequest_HelicopterTemplate
	//	*AddGroupRequest_PlaneTemplate
	Template isAddGroupRequest_Template `protobuf_oneof:"template"`
}

func (x *AddGroupRequest) Reset() {
	*x = AddGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGroupRequest) ProtoMessage() {}

func (x *AddGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGroupRequest.ProtoReflect.Descriptor instead.
func (*AddGroupRequest) Descriptor() ([]byte, []int) {
	return file_dcs_coalition_v0_coalition_proto_rawDescGZIP(), []int{0}
}

func (x *AddGroupRequest) GetCountry() common.Country {
	if x != nil {
		return x.Country
	}
	return common.Country(0)
}

func (x *AddGroupRequest) GetGroupCategory() common.GroupCategory {
	if x != nil {
		return x.GroupCategory
	}
	return common.GroupCategory(0)
}

func (m *AddGroupRequest) GetTemplate() isAddGroupRequest_Template {
	if m != nil {
		return m.Template
	}
	return nil
}

func (x *AddGroupRequest) GetGroundTemplate() *AddGroupRequest_GroundGroupTemplate {
	if x, ok := x.GetTemplate().(*AddGroupRequest_GroundTemplate); ok {
		return x.GroundTemplate
	}
	return nil
}

func (x *AddGroupRequest) GetShipTemplate() *AddGroupRequest_ShipGroupTemplate {
	if x, ok := x.GetTemplate().(*AddGroupRequest_ShipTemplate); ok {
		return x.ShipTemplate
	}
	return nil
}

func (x *AddGroupRequest) GetHelicopterTemplate() *AddGroupRequest_HelicopterGroupTemplate {
	if x, ok := x.GetTemplate().(*AddGroupRequest_HelicopterTemplate); ok {
		return x.HelicopterTemplate
	}
	return nil
}

func (x *AddGroupRequest) GetPlaneTemplate() *AddGroupRequest_PlaneGroupTemplate {
	if x, ok := x.GetTemplate().(*AddGroupRequest_PlaneTemplate); ok {
		return x.PlaneTemplate
	}
	return nil
}

type isAddGroupRequest_Template interface {
	isAddGroupRequest_Template()
}

type AddGroupRequest_GroundTemplate struct {
	GroundTemplate *AddGroupRequest_GroundGroupTemplate `protobuf:"bytes,4,opt,name=ground_template,json=groundTemplate,proto3,oneof"`
}

type AddGroupRequest_ShipTemplate struct {
	ShipTemplate *AddGroupRequest_ShipGroupTemplate `protobuf:"bytes,5,opt,name=ship_template,json=shipTemplate,proto3,oneof"`
}

type AddGroupRequest_HelicopterTemplate struct {
	HelicopterTemplate *AddGroupRequest_HelicopterGroupTemplate `protobuf:"bytes,6,opt,name=helicopter_template,json=helicopterTemplate,proto3,oneof"`
}

type AddGroupRequest_PlaneTemplate struct {
	PlaneTemplate *AddGroupRequest_PlaneGroupTemplate `protobuf:"bytes,7,opt,name=plane_template,json=planeTemplate,proto3,oneof"`
}

func (*AddGroupRequest_GroundTemplate) isAddGroupRequest_Template() {}

func (*AddGroupRequest_ShipTemplate) isAddGroupRequest_Template() {}

func (*AddGroupRequest_HelicopterTemplate) isAddGroupRequest_Template() {}

func (*AddGroupRequest_PlaneTemplate) isAddGroupRequest_Template() {}

type AddGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group *common.Group `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
}

func (x *AddGroupResponse) Reset() {
	*x = AddGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGroupResponse) ProtoMessage() {}

func (x *AddGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGroupResponse.ProtoReflect.Descriptor instead.
func (*AddGroupResponse) Descriptor() ([]byte, []int) {
	return file_dcs_coalition_v0_coalition_proto_rawDescGZIP(), []int{1}
}

func (x *AddGroupResponse) GetGroup() *common.Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type GetStaticObjectsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// the coalition which the statics belong to
	Coalition common.Coalition `protobuf:"varint,1,opt,name=coalition,proto3,enum=dcs.common.v0.Coalition" json:"coalition,omitempty"`
}

func (x *GetStaticObjectsRequest) Reset() {
	*x = GetStaticObjectsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStaticObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStaticObjectsRequest) ProtoMessage() {}

func (x *GetStaticObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStaticObjectsRequest.ProtoReflect.Descriptor instead.
func (*GetStaticObjectsRequest) Descriptor() ([]byte, []int) {
	return file_dcs_coalition_v0_coalition_proto_rawDescGZIP(), []int{2}
}

func (x *GetStaticObjectsRequest) GetCoalition() common.Coalition {
	if x != nil {
		return x.Coalition
	}
	return common.Coalition(0)
}

type GetStaticObjectsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// the list of statics
	Statics []*common.Static `protobuf:"bytes,1,rep,name=statics,proto3" json:"statics,omitempty"`
}

func (x *GetStaticObjectsResponse) Reset() {
	*x = GetStaticObjectsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStaticObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStaticObjectsResponse) ProtoMessage() {}

func (x *GetStaticObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStaticObjectsResponse.ProtoReflect.Descriptor instead.
func (*GetStaticObjectsResponse) Descriptor() ([]byte, []int) {
	return file_dcs_coalition_v0_coalition_proto_rawDescGZIP(), []int{3}
}

func (x *GetStaticObjectsResponse) GetStatics() []*common.Static {
	if x != nil {
		return x.Statics
	}
	return nil
}

type AddStaticObjectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// the name of the static; must be unique or would destroy previous object
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// country the unit belongs to
	Country common.Country `protobuf:"varint,2,opt,name=country,proto3,enum=dcs.common.v0.Country" json:"country,omitempty"`
	// type of the static object (e.g. "Farm A", "AS32-31A")
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// string name of the livery for the aircraft
	Livery string `protobuf:"bytes,4,opt,name=livery,proto3" json:"livery,omitempty"`
	// boolean for whether or not the object will appear as a wreck
	Dead bool `protobuf:"varint,5,opt,name=dead,proto3" json:"dead,omitempty"`
	// number value for the "score" of the object when it is killed
	Rate     *uint32               `protobuf:"varint,6,opt,name=rate,proto3,oneof" json:"rate,omitempty"`
	Heading  float64               `protobuf:"fixed64,7,opt,name=heading,proto3" json:"heading,omitempty"`
	Position *common.InputPosition `protobuf:"bytes,8,opt,name=position,proto3" json:"position,omitempty"`
	// cargo mass in kilograms
	CargoMass uint32 `protobuf:"varint,9,opt,name=cargo_mass,json=cargoMass,proto3" json:"cargo_mass,omitempty"`
}

func (x *AddStaticObjectRequest) Reset() {
	*x = AddStaticObjectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddStaticObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStaticObjectRequest) ProtoMessage() {}

func (x *AddStaticObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStaticObjectRequest.ProtoReflect.Descriptor instead.
func (*AddStaticObjectRequest) Descriptor() ([]byte, []int) {
	return file_dcs_coalition_v0_coalition_proto_rawDescGZIP(), []int{4}
}

func (x *AddStaticObjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddStaticObjectRequest) GetCountry() common.Country {
	if x != nil {
		return x.Country
	}
	return common.Country(0)
}

func (x *AddStaticObjectRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AddStaticObjectRequest) GetLivery() string {
	if x != nil {
		return x.Livery
	}
	return ""
}

func (x *AddStaticObjectRequest) GetDead() bool {
	if x != nil {
		return x.Dead
	}
	return false
}

func (x *AddStaticObjectRequest) GetRate() uint32 {
	if x != nil && x.Rate != nil {
		return *x.Rate
	}
	return 0
}

func (x *AddStaticObjectRequest) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *AddStaticObjectRequest) GetPosition() *common.InputPosition {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *AddStaticObjectRequest) GetCargoMass() uint32 {
	if x != nil {
		return x.CargoMass
	}
	return 0
}

type AddStaticObjectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *AddStaticObjectResponse) Reset() {
	*x = AddStaticObjectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddStaticObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStaticObjectResponse) ProtoMessage() {}

func (x *AddStaticObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStaticObjectResponse.ProtoReflect.Descriptor instead.
func (*AddStaticObjectResponse) Descriptor() ([]byte, []int) {
	return file_dcs_coalition_v0_coalition_proto_rawDescGZIP(), []int{5}
}

func (x *AddStaticObjectResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AddLinkedStaticRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// the name of the static; must be unique or would destroy previous object
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// country the unit belongs to
	Country common.Country `protobuf:"varint,2,opt,name=country,proto3,enum=dcs.common.v0.Country" json:"country,omitempty"`
	// type of the static object (e.g. "Farm A", "AS32-31A")
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// string name of the livery for the aircraft
	Livery string `protobuf:"bytes,4,opt,name=livery,proto3" json:"livery,omitempty"`
	// boolean for whether or not the object will appear as a wreck
	Dead bool `protobuf:"varint,5,opt,name=dead,proto3" json:"dead,omitempty"`
	// number value for the "score" of the object when it is killed
	Rate *uint32 `protobuf:"varint,6,opt,name=rate,proto3,oneof" json:"rate,omitempty"`
	// the name of the unit to offset from
	Unit string `protobuf:"bytes,7,opt,name=unit,proto3" json:"unit,omitempty"`
	// the angle to relative to the linked unit, in a clockwise direction.
	// negative values are anti-clockwise
	Angle float64 `protobuf:"fixed64,8,opt,name=angle,proto3" json:"angle,omitempty"`
	// x offset from linked unit center (positive is forward; negative is aft)
	X float64 `protobuf:"fixed64,9,opt,name=x,proto3" json:"x,omitempty"`
	// y offset from linked unit center (positive is starboard-side;
	// negative is port-side)
	Y float64 `protobuf:"fixed64,10,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *AddLinkedStaticRequest) Reset() {
	*x = AddLinkedStaticRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddLinkedStaticRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLinkedStaticRequest) ProtoMessage() {}

func (x *AddLinkedStaticRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLinkedStaticRequest.ProtoReflect.Descriptor instead.
func (*AddLinkedStaticRequest) Descriptor() ([]byte, []int) {
	return file_dcs_coalition_v0_coalition_proto_rawDescGZIP(), []int{6}
}

func (x *AddLinkedStaticRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddLinkedStaticRequest) GetCountry() common.Country {
	if x != nil {
		return x.Country
	}
	return common.Country(0)
}

func (x *AddLinkedStaticRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AddLinkedStaticRequest) GetLivery() string {
	if x != nil {
		return x.Livery
	}
	return ""
}

func (x *AddLinkedStaticRequest) GetDead() bool {
	if x != nil {
		return x.Dead
	}
	return false
}

func (x *AddLinkedStaticRequest) GetRate() uint32 {
	if x != nil && x.Rate != nil {
		return *x.Rate
	}
	return 0
}

func (x *AddLinkedStaticRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *AddLinkedStaticRequest) GetAngle() float64 {
	if x != nil {
		return x.Angle
	}
	return 0
}

func (x *AddLinkedStaticRequest) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *AddLinkedStaticRequest) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type AddLinkedStaticResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *AddLinkedStaticResponse) Reset() {
	*x = AddLinkedStaticResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddLinkedStaticResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLinkedStaticResponse) ProtoMessage() {}

func (x *AddLinkedStaticResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLinkedStaticResponse.ProtoReflect.Descriptor instead.
func (*AddLinkedStaticResponse) Descriptor() ([]byte, []int) {
	return file_dcs_coalition_v0_coalition_proto_rawDescGZIP(), []int{7}
}

func (x *AddLinkedStaticResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetGroupsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coalition common.Coalition     `protobuf:"varint,1,opt,name=coalition,proto3,enum=dcs.common.v0.Coalition" json:"coalition,omitempty"`
	Category  common.GroupCategory `protobuf:"varint,2,opt,name=category,proto3,enum=dcs.common.v0.GroupCategory" json:"category,omitempty"`
}

func (x *GetGroupsRequest) Reset() {
	*x = GetGroupsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupsRequest) ProtoMessage() {}

func (x *GetGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupsRequest.ProtoReflect.Descriptor instead.
func (*GetGroupsRequest) Descriptor() ([]byte, []int) {
	return file_dcs_coalition_v0_coalition_proto_rawDescGZIP(), []int{8}
}

func (x *GetGroupsRequest) GetCoalition() common.Coalition {
	if x != nil {
		return x.Coalition
	}
	return common.Coalition(0)
}

func (x *GetGroupsRequest) GetCategory() common.GroupCategory {
	if x != nil {
		return x.Category
	}
	return common.GroupCategory(0)
}

type GetGroupsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Groups []*common.Group `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
}

func (x *GetGroupsResponse) Reset() {
	*x = GetGroupsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupsResponse) ProtoMessage() {}

func (x *GetGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupsResponse.ProtoReflect.Descriptor instead.
func (*GetGroupsResponse) Descriptor() ([]byte, []int) {
	return file_dcs_coalition_v0_coalition_proto_rawDescGZIP(), []int{9}
}

func (x *GetGroupsResponse) GetGroups() []*common.Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

type GetBullseyeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A specific coalition must be used for this API call. Do not use
	// `COALITION_ALL`
	Coalition common.Coalition `protobuf:"varint,1,opt,name=coalition,proto3,enum=dcs.common.v0.Coalition" json:"coalition,omitempty"`
}

func (x *GetBullseyeRequest) Reset() {
	*x = GetBullseyeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBullseyeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBullseyeRequest) ProtoMessage() {}

func (x *GetBullseyeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBullseyeRequest.ProtoReflect.Descriptor instead.
func (*GetBullseyeRequest) Descriptor() ([]byte, []int) {
	return file_dcs_coalition_v0_coalition_proto_rawDescGZIP(), []int{10}
}

func (x *GetBullseyeRequest) GetCoalition() common.Coalition {
	if x != nil {
		return x.Coalition
	}
	return common.Coalition(0)
}

type GetBullseyeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position *common.Position `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *GetBullseyeResponse) Reset() {
	*x = GetBullseyeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBullseyeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBullseyeResponse) ProtoMessage() {}

func (x *GetBullseyeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBullseyeResponse.ProtoReflect.Descriptor instead.
func (*GetBullseyeResponse) Descriptor() ([]byte, []int) {
	return file_dcs_coalition_v0_coalition_proto_rawDescGZIP(), []int{11}
}

func (x *GetBullseyeResponse) GetPosition() *common.Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type GetPlayerUnitsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coalition common.Coalition `protobuf:"varint,1,opt,name=coalition,proto3,enum=dcs.common.v0.Coalition" json:"coalition,omitempty"`
}

func (x *GetPlayerUnitsRequest) Reset() {
	*x = GetPlayerUnitsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlayerUnitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerUnitsRequest) ProtoMessage() {}

func (x *GetPlayerUnitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerUnitsRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerUnitsRequest) Descriptor() ([]byte, []int) {
	return file_dcs_coalition_v0_coalition_proto_rawDescGZIP(), []int{12}
}

func (x *GetPlayerUnitsRequest) GetCoalition() common.Coalition {
	if x != nil {
		return x.Coalition
	}
	return common.Coalition(0)
}

type GetPlayerUnitsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Units []*common.Unit `protobuf:"bytes,1,rep,name=units,proto3" json:"units,omitempty"`
}

func (x *GetPlayerUnitsResponse) Reset() {
	*x = GetPlayerUnitsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlayerUnitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerUnitsResponse) ProtoMessage() {}

func (x *GetPlayerUnitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerUnitsResponse.ProtoReflect.Descriptor instead.
func (*GetPlayerUnitsResponse) Descriptor() ([]byte, []int) {
	return file_dcs_coalition_v0_coalition_proto_rawDescGZIP(), []int{13}
}

func (x *GetPlayerUnitsResponse) GetUnits() []*common.Unit {
	if x != nil {
		return x.Units
	}
	return nil
}

type AddGroupRequest_GroundGroupTemplate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId        *uint32                               `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3,oneof" json:"group_id,omitempty"`
	Hidden         bool                                  `protobuf:"varint,2,opt,name=hidden,proto3" json:"hidden,omitempty"`
	LateActivation bool                                  `protobuf:"varint,3,opt,name=late_activation,json=lateActivation,proto3" json:"late_activation,omitempty"`
	Name           string                                `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Position       *common.InputPosition                 `protobuf:"bytes,5,opt,name=position,proto3" json:"position,omitempty"`
	Waypoints      []*AddGroupRequest_Point              `protobuf:"bytes,6,rep,name=waypoints,proto3" json:"waypoints,omitempty"`
	StartTime      uint32                                `protobuf:"varint,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Task           string                                `protobuf:"bytes,8,opt,name=task,proto3" json:"task,omitempty"`
	TaskSelected   bool                                  `protobuf:"varint,9,opt,name=task_selected,json=taskSelected,proto3" json:"task_selected,omitempty"`
	Tasks          []*AddGroupRequest_Task               `protobuf:"bytes,10,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Uncontrollable bool                                  `protobuf:"varint,11,opt,name=uncontrollable,proto3" json:"uncontrollable,omitempty"`
	Units          []*AddGroupRequest_GroundUnitTemplate `protobuf:"bytes,12,rep,name=units,proto3" json:"units,omitempty"`
	Visible        bool                                  `protobuf:"varint,13,opt,name=visible,proto3" json:"visible,omitempty"`
}

func (x *AddGroupRequest_GroundGroupTemplate) Reset() {
	*x = AddGroupRequest_GroundGroupTemplate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGroupRequest_GroundGroupTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGroupRequest_GroundGroupTemplate) ProtoMessage() {}

func (x *AddGroupRequest_GroundGroupTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGroupRequest_GroundGroupTemplate.ProtoReflect.Descriptor instead.
func (*AddGroupRequest_GroundGroupTemplate) Descriptor() ([]byte, []int) {
	return file_dcs_coalition_v0_coalition_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AddGroupRequest_GroundGroupTemplate) GetGroupId() uint32 {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return 0
}

func (x *AddGroupRequest_GroundGroupTemplate) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *AddGroupRequest_GroundGroupTemplate) GetLateActivation() bool {
	if x != nil {
		return x.LateActivation
	}
	return false
}

func (x *AddGroupRequest_GroundGroupTemplate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddGroupRequest_GroundGroupTemplate) GetPosition() *common.InputPosition {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *AddGroupRequest_GroundGroupTemplate) GetWaypoints() []*AddGroupRequest_Point {
	if x != nil {
		return x.Waypoints
	}
	return nil
}

func (x *AddGroupRequest_GroundGroupTemplate) GetStartTime() uint32 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *AddGroupRequest_GroundGroupTemplate) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *AddGroupRequest_GroundGroupTemplate) GetTaskSelected() bool {
	if x != nil {
		return x.TaskSelected
	}
	return false
}

func (x *AddGroupRequest_GroundGroupTemplate) GetTasks() []*AddGroupRequest_Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *AddGroupRequest_GroundGroupTemplate) GetUncontrollable() bool {
	if x != nil {
		return x.Uncontrollable
	}
	return false
}

func (x *AddGroupRequest_GroundGroupTemplate) GetUnits() []*AddGroupRequest_GroundUnitTemplate {
	if x != nil {
		return x.Units
	}
	return nil
}

func (x *AddGroupRequest_GroundGroupTemplate) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

type AddGroupRequest_GroundUnitTemplate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type     string                `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Position *common.InputPosition `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	UnitId   *uint32               `protobuf:"varint,4,opt,name=unit_id,json=unitId,proto3,oneof" json:"unit_id,omitempty"`
	Heading  *uint32               `protobuf:"varint,5,opt,name=heading,proto3,oneof" json:"heading,omitempty"`
	Skill    AddGroupRequest_Skill `protobuf:"varint,6,opt,name=skill,proto3,enum=dcs.coalition.v0.AddGroupRequest_Skill" json:"skill,omitempty"`
}

func (x *AddGroupRequest_GroundUnitTemplate) Reset() {
	*x = AddGroupRequest_GroundUnitTemplate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGroupRequest_GroundUnitTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGroupRequest_GroundUnitTemplate) ProtoMessage() {}

func (x *AddGroupRequest_GroundUnitTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGroupRequest_GroundUnitTemplate.ProtoReflect.Descriptor instead.
func (*AddGroupRequest_GroundUnitTemplate) Descriptor() ([]byte, []int) {
	return file_dcs_coalition_v0_coalition_proto_rawDescGZIP(), []int{0, 1}
}

func (x *AddGroupRequest_GroundUnitTemplate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddGroupRequest_GroundUnitTemplate) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AddGroupRequest_GroundUnitTemplate) GetPosition() *common.InputPosition {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *AddGroupRequest_GroundUnitTemplate) GetUnitId() uint32 {
	if x != nil && x.UnitId != nil {
		return *x.UnitId
	}
	return 0
}

func (x *AddGroupRequest_GroundUnitTemplate) GetHeading() uint32 {
	if x != nil && x.Heading != nil {
		return *x.Heading
	}
	return 0
}

func (x *AddGroupRequest_GroundUnitTemplate) GetSkill() AddGroupRequest_Skill {
	if x != nil {
		return x.Skill
	}
	return AddGroupRequest_SKILL_RANDOM
}

type AddGroupRequest_ShipGroupTemplate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddGroupRequest_ShipGroupTemplate) Reset() {
	*x = AddGroupRequest_ShipGroupTemplate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGroupRequest_ShipGroupTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGroupRequest_ShipGroupTemplate) ProtoMessage() {}

func (x *AddGroupRequest_ShipGroupTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGroupRequest_ShipGroupTemplate.ProtoReflect.Descriptor instead.
func (*AddGroupRequest_ShipGroupTemplate) Descriptor() ([]byte, []int) {
	return file_dcs_coalition_v0_coalition_proto_rawDescGZIP(), []int{0, 2}
}

type AddGroupRequest_ShipUnitTemplate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddGroupRequest_ShipUnitTemplate) Reset() {
	*x = AddGroupRequest_ShipUnitTemplate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGroupRequest_ShipUnitTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGroupRequest_ShipUnitTemplate) ProtoMessage() {}

func (x *AddGroupRequest_ShipUnitTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGroupRequest_ShipUnitTemplate.ProtoReflect.Descriptor instead.
func (*AddGroupRequest_ShipUnitTemplate) Descriptor() ([]byte, []int) {
	return file_dcs_coalition_v0_coalition_proto_rawDescGZIP(), []int{0, 3}
}

type AddGroupRequest_HelicopterGroupTemplate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddGroupRequest_HelicopterGroupTemplate) Reset() {
	*x = AddGroupRequest_HelicopterGroupTemplate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGroupRequest_HelicopterGroupTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGroupRequest_HelicopterGroupTemplate) ProtoMessage() {}

func (x *AddGroupRequest_HelicopterGroupTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGroupRequest_HelicopterGroupTemplate.ProtoReflect.Descriptor instead.
func (*AddGroupRequest_HelicopterGroupTemplate) Descriptor() ([]byte, []int) {
	return file_dcs_coalition_v0_coalition_proto_rawDescGZIP(), []int{0, 4}
}

type AddGroupRequest_HelicopterUnitTemplate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddGroupRequest_HelicopterUnitTemplate) Reset() {
	*x = AddGroupRequest_HelicopterUnitTemplate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGroupRequest_HelicopterUnitTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGroupRequest_HelicopterUnitTemplate) ProtoMessage() {}

func (x *AddGroupRequest_HelicopterUnitTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGroupRequest_HelicopterUnitTemplate.ProtoReflect.Descriptor instead.
func (*AddGroupRequest_HelicopterUnitTemplate) Descriptor() ([]byte, []int) {
	return file_dcs_coalition_v0_coalition_proto_rawDescGZIP(), []int{0, 5}
}

type AddGroupRequest_PlaneGroupTemplate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddGroupRequest_PlaneGroupTemplate) Reset() {
	*x = AddGroupRequest_PlaneGroupTemplate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGroupRequest_PlaneGroupTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGroupRequest_PlaneGroupTemplate) ProtoMessage() {}

func (x *AddGroupRequest_PlaneGroupTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGroupRequest_PlaneGroupTemplate.ProtoReflect.Descriptor instead.
func (*AddGroupRequest_PlaneGroupTemplate) Descriptor() ([]byte, []int) {
	return file_dcs_coalition_v0_coalition_proto_rawDescGZIP(), []int{0, 6}
}

type AddGroupRequest_PlaneUnitTemplate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddGroupRequest_PlaneUnitTemplate) Reset() {
	*x = AddGroupRequest_PlaneUnitTemplate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGroupRequest_PlaneUnitTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGroupRequest_PlaneUnitTemplate) ProtoMessage() {}

func (x *AddGroupRequest_PlaneUnitTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGroupRequest_PlaneUnitTemplate.ProtoReflect.Descriptor instead.
func (*AddGroupRequest_PlaneUnitTemplate) Descriptor() ([]byte, []int) {
	return file_dcs_coalition_v0_coalition_proto_rawDescGZIP(), []int{0, 7}
}

type AddGroupRequest_Point struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position     *common.InputPosition              `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	AltitudeType AddGroupRequest_Point_AltitudeType `protobuf:"varint,2,opt,name=altitude_type,json=altitudeType,proto3,enum=dcs.coalition.v0.AddGroupRequest_Point_AltitudeType" json:"altitude_type,omitempty"`
	Type         AddGroupRequest_Point_PointType    `protobuf:"varint,3,opt,name=type,proto3,enum=dcs.coalition.v0.AddGroupRequest_Point_PointType" json:"type,omitempty"`
	Action       string                             `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Form         string                             `protobuf:"bytes,5,opt,name=form,proto3" json:"form,omitempty"`
	Speed        float64                            `protobuf:"fixed64,6,opt,name=speed,proto3" json:"speed,omitempty"`
}

func (x *AddGroupRequest_Point) Reset() {
	*x = AddGroupRequest_Point{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGroupRequest_Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGroupRequest_Point) ProtoMessage() {}

func (x *AddGroupRequest_Point) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGroupRequest_Point.ProtoReflect.Descriptor instead.
func (*AddGroupRequest_Point) Descriptor() ([]byte, []int) {
	return file_dcs_coalition_v0_coalition_proto_rawDescGZIP(), []int{0, 8}
}

func (x *AddGroupRequest_Point) GetPosition() *common.InputPosition {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *AddGroupRequest_Point) GetAltitudeType() AddGroupRequest_Point_AltitudeType {
	if x != nil {
		return x.AltitudeType
	}
	return AddGroupRequest_Point_ALTITUDE_TYPE_UNSPECIFIED
}

func (x *AddGroupRequest_Point) GetType() AddGroupRequest_Point_PointType {
	if x != nil {
		return x.Type
	}
	return AddGroupRequest_Point_POINT_TYPE_RANDOM
}

func (x *AddGroupRequest_Point) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AddGroupRequest_Point) GetForm() string {
	if x != nil {
		return x.Form
	}
	return ""
}

func (x *AddGroupRequest_Point) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type AddGroupRequest_Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddGroupRequest_Task) Reset() {
	*x = AddGroupRequest_Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGroupRequest_Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGroupRequest_Task) ProtoMessage() {}

func (x *AddGroupRequest_Task) ProtoReflect() protoreflect.Message {
	mi := &file_dcs_coalition_v0_coalition_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGroupRequest_Task.ProtoReflect.Descriptor instead.
func (*AddGroupRequest_Task) Descriptor() ([]byte, []int) {
	return file_dcs_coalition_v0_coalition_proto_rawDescGZIP(), []int{0, 9}
}

var File_dcs_coalition_v0_coalition_proto protoreflect.FileDescriptor

var file_dcs_coalition_v0_coalition_proto_rawDesc = []byte{
	0x0a, 0x20, 0x64, 0x63, 0x73, 0x2f, 0x63, 0x6f, 0x61, 0x6c, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2f,
	0x76, 0x30, 0x2f, 0x63, 0x6f, 0x61, 0x6c, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x10, 0x64, 0x63, 0x73, 0x2e, 0x63, 0x6f, 0x61, 0x6c, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x76, 0x30, 0x1a, 0x1a, 0x64, 0x63, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2f, 0x76, 0x30, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xb3, 0x11, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x43, 0x0a, 0x0e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c,
	0x2e, 0x64, 0x63, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x0d, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x60, 0x0a, 0x0f, 0x67,
	0x72, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x63, 0x6f, 0x61, 0x6c, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x41, 0x64, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x0e, 0x67,
	0x72, 0x6f, 0x75, 0x6e, 0x64, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x5a, 0x0a,
	0x0d, 0x73, 0x68, 0x69, 0x70, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x63, 0x6f, 0x61, 0x6c, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x41, 0x64, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x68, 0x69, 0x70, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x73, 0x68, 0x69,
	0x70, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x6c, 0x0a, 0x13, 0x68, 0x65, 0x6c,
	0x69, 0x63, 0x6f, 0x70, 0x74, 0x65, 0x72, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x39, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x63, 0x6f, 0x61,
	0x6c, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x41, 0x64, 0x64, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x48, 0x65, 0x6c, 0x69, 0x63, 0x6f,
	0x70, 0x74, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x48, 0x00, 0x52, 0x12, 0x68, 0x65, 0x6c, 0x69, 0x63, 0x6f, 0x70, 0x74, 0x65, 0x72, 0x54,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x5d, 0x0a, 0x0e, 0x70, 0x6c, 0x61, 0x6e, 0x65,
	0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x34, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x63, 0x6f, 0x61, 0x6c, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x76, 0x30, 0x2e, 0x41, 0x64, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x54, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x1a, 0xbc, 0x04, 0x0a, 0x13, 0x47, 0x72, 0x6f, 0x75, 0x6e,
	0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x1e,
	0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x48, 0x00, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x16,
	0x0a, 0x06, 0x68, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x68, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x12, 0x27, 0x0a, 0x0f, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0e, 0x6c, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x38, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x50, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x45, 0x0a,
	0x09, 0x77, 0x61, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x27, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x63, 0x6f, 0x61, 0x6c, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x76, 0x30, 0x2e, 0x41, 0x64, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x09, 0x77, 0x61, 0x79, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x61, 0x73, 0x6b, 0x5f,
	0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c,
	0x74, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x3c, 0x0a, 0x05,
	0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x64, 0x63,
	0x73, 0x2e, 0x63, 0x6f, 0x61, 0x6c, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x41,
	0x64, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x54,
	0x61, 0x73, 0x6b, 0x52, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x75, 0x6e,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0e, 0x75, 0x6e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x61, 0x62,
	0x6c, 0x65, 0x12, 0x4a, 0x0a, 0x05, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x18, 0x0c, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x34, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x63, 0x6f, 0x61, 0x6c, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x41, 0x64, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x55, 0x6e, 0x69, 0x74, 0x54,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x05, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x76, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x5f, 0x69, 0x64, 0x1a, 0x8a, 0x02, 0x0a, 0x12, 0x47, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x55, 0x6e, 0x69, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x38, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x50, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c,
	0x0a, 0x07, 0x75, 0x6e, 0x69, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x48,
	0x00, 0x52, 0x06, 0x75, 0x6e, 0x69, 0x74, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07,
	0x68, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x01, 0x52,
	0x07, 0x68, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x88, 0x01, 0x01, 0x12, 0x3d, 0x0a, 0x05, 0x73,
	0x6b, 0x69, 0x6c, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x64, 0x63, 0x73,
	0x2e, 0x63, 0x6f, 0x61, 0x6c, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x41, 0x64,
	0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x6b,
	0x69, 0x6c, 0x6c, 0x52, 0x05, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x75,
	0x6e, 0x69, 0x74, 0x5f, 0x69, 0x64, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x69,
	0x6e, 0x67, 0x1a, 0x13, 0x0a, 0x11, 0x53, 0x68, 0x69, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x1a, 0x12, 0x0a, 0x10, 0x53, 0x68, 0x69, 0x70, 0x55,
	0x6e, 0x69, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x1a, 0x19, 0x0a, 0x17, 0x48,
	0x65, 0x6c, 0x69, 0x63, 0x6f, 0x70, 0x74, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x1a, 0x18, 0x0a, 0x16, 0x48, 0x65, 0x6c, 0x69, 0x63, 0x6f,
	0x70, 0x74, 0x65, 0x72, 0x55, 0x6e, 0x69, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x1a, 0x14, 0x0a, 0x12, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x1a, 0x13, 0x0a, 0x11, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x55,
	0x6e, 0x69, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x1a, 0xbf, 0x04, 0x0a, 0x05,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x38, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x50, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x59, 0x0a, 0x0d, 0x61, 0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x34, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x63, 0x6f, 0x61,
	0x6c, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x41, 0x64, 0x64, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x2e,
	0x41, 0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c, 0x61, 0x6c,
	0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x45, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x31, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x63,
	0x6f, 0x61, 0x6c, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x41, 0x64, 0x64, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6f, 0x72,
	0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x70,
	0x65, 0x65, 0x64, 0x22, 0x64, 0x0a, 0x0c, 0x41, 0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x19, 0x41, 0x4c, 0x54, 0x49, 0x54, 0x55, 0x44, 0x45, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x1c, 0x0a, 0x18, 0x41, 0x4c, 0x54, 0x49, 0x54, 0x55, 0x44, 0x45, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x42, 0x41, 0x52, 0x4f, 0x4d, 0x45, 0x54, 0x52, 0x49, 0x43, 0x10, 0x01,
	0x12, 0x17, 0x0a, 0x13, 0x41, 0x4c, 0x54, 0x49, 0x54, 0x55, 0x44, 0x45, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x52, 0x41, 0x44, 0x49, 0x4f, 0x10, 0x02, 0x22, 0xb1, 0x01, 0x0a, 0x09, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x50, 0x4f, 0x49, 0x4e, 0x54,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x41, 0x4e, 0x44, 0x4f, 0x4d, 0x10, 0x00, 0x12, 0x16,
	0x0a, 0x12, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x54, 0x41, 0x4b,
	0x45, 0x4f, 0x46, 0x46, 0x10, 0x01, 0x12, 0x1e, 0x0a, 0x1a, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x54, 0x41, 0x4b, 0x45, 0x4f, 0x46, 0x46, 0x5f, 0x50, 0x41, 0x52,
	0x4b, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x1c, 0x0a, 0x18, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x54, 0x55, 0x52, 0x4e, 0x49, 0x4e, 0x47, 0x5f, 0x50, 0x4f, 0x49,
	0x4e, 0x54, 0x10, 0x03, 0x12, 0x22, 0x0a, 0x1e, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x54, 0x41, 0x4b, 0x45, 0x4f, 0x46, 0x46, 0x5f, 0x50, 0x41, 0x52, 0x4b, 0x49,
	0x4e, 0x47, 0x5f, 0x48, 0x4f, 0x54, 0x10, 0x04, 0x12, 0x13, 0x0a, 0x0f, 0x50, 0x4f, 0x49, 0x4e,
	0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4c, 0x41, 0x4e, 0x44, 0x10, 0x05, 0x1a, 0x06, 0x0a,
	0x04, 0x54, 0x61, 0x73, 0x6b, 0x22, 0x73, 0x0a, 0x05, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x12, 0x10,
	0x0a, 0x0c, 0x53, 0x4b, 0x49, 0x4c, 0x4c, 0x5f, 0x52, 0x41, 0x4e, 0x44, 0x4f, 0x4d, 0x10, 0x00,
	0x12, 0x11, 0x0a, 0x0d, 0x53, 0x4b, 0x49, 0x4c, 0x4c, 0x5f, 0x41, 0x56, 0x45, 0x52, 0x41, 0x47,
	0x45, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x4b, 0x49, 0x4c, 0x4c, 0x5f, 0x47, 0x4f, 0x4f,
	0x44, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x4b, 0x49, 0x4c, 0x4c, 0x5f, 0x48, 0x49, 0x47,
	0x48, 0x10, 0x03, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x4b, 0x49, 0x4c, 0x4c, 0x5f, 0x45, 0x58, 0x43,
	0x45, 0x4c, 0x4c, 0x45, 0x4e, 0x54, 0x10, 0x04, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x4b, 0x49, 0x4c,
	0x4c, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x10, 0x05, 0x42, 0x0a, 0x0a, 0x08, 0x74, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x22, 0x3e, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x05, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x63, 0x73, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52,
	0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x22, 0x51, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x69, 0x63, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x36, 0x0a, 0x09, 0x63, 0x6f, 0x61, 0x6c, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x43, 0x6f, 0x61, 0x6c, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09,
	0x63, 0x6f, 0x61, 0x6c, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4b, 0x0a, 0x18, 0x47, 0x65, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x74, 0x69, 0x63, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x52, 0x07, 0x73,
	0x74, 0x61, 0x74, 0x69, 0x63, 0x73, 0x22, 0xb3, 0x02, 0x0a, 0x16, 0x41, 0x64, 0x64, 0x53, 0x74,
	0x61, 0x74, 0x69, 0x63, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x30, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6c,
	0x69, 0x76, 0x65, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x69, 0x76,
	0x65, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x61, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x04, 0x64, 0x65, 0x61, 0x64, 0x12, 0x17, 0x0a, 0x04, 0x72, 0x61, 0x74, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x04, 0x72, 0x61, 0x74, 0x65, 0x88, 0x01, 0x01,
	0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x38, 0x0a, 0x08, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x64,
	0x63, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x5f, 0x6d, 0x61,
	0x73, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x4d,
	0x61, 0x73, 0x73, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x22, 0x2d, 0x0a, 0x17,
	0x41, 0x64, 0x64, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x86, 0x02, 0x0a, 0x16,
	0x41, 0x64, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x30, 0x0a, 0x07, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x64, 0x63,
	0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x61, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64, 0x65, 0x61, 0x64, 0x12, 0x17, 0x0a, 0x04,
	0x72, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x04, 0x72, 0x61,
	0x74, 0x65, 0x88, 0x01, 0x01, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6e, 0x67,
	0x6c, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x12,
	0x0c, 0x0a, 0x01, 0x78, 0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a,
	0x01, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x79, 0x42, 0x07, 0x0a, 0x05, 0x5f,
	0x72, 0x61, 0x74, 0x65, 0x22, 0x2d, 0x0a, 0x17, 0x41, 0x64, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x65,
	0x64, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x84, 0x01, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x09, 0x63, 0x6f, 0x61, 0x6c,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x64, 0x63,
	0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x43, 0x6f, 0x61, 0x6c,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x63, 0x6f, 0x61, 0x6c, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x38, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x76, 0x30, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0x41, 0x0a, 0x11, 0x47, 0x65,
	0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2c, 0x0a, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x2e,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x22, 0x4c, 0x0a,
	0x12, 0x47, 0x65, 0x74, 0x42, 0x75, 0x6c, 0x6c, 0x73, 0x65, 0x79, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x09, 0x63, 0x6f, 0x61, 0x6c, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x43, 0x6f, 0x61, 0x6c, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x09, 0x63, 0x6f, 0x61, 0x6c, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4a, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x42, 0x75, 0x6c, 0x6c, 0x73, 0x65, 0x79, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x33, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4f, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x55, 0x6e, 0x69, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x36, 0x0a, 0x09, 0x63, 0x6f, 0x61, 0x6c, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x76, 0x30, 0x2e, 0x43, 0x6f, 0x61, 0x6c, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x63,
	0x6f, 0x61, 0x6c, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x43, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x55, 0x6e, 0x69, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76,
	0x30, 0x2e, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x05, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x32, 0xc5, 0x05,
	0x0a, 0x10, 0x43, 0x6f, 0x61, 0x6c, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x53, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x21,
	0x2e, 0x64, 0x63, 0x73, 0x2e, 0x63, 0x6f, 0x61, 0x6c, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76,
	0x30, 0x2e, 0x41, 0x64, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x22, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x63, 0x6f, 0x61, 0x6c, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x41, 0x64, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6b, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x69, 0x63, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x12, 0x29, 0x2e, 0x64, 0x63,
	0x73, 0x2e, 0x63, 0x6f, 0x61, 0x6c, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x63, 0x6f, 0x61,
	0x6c, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x69, 0x63, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x68, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x53, 0x74, 0x61, 0x74, 0x69,
	0x63, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x28, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x63, 0x6f,
	0x61, 0x6c, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x74,
	0x61, 0x74, 0x69, 0x63, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x29, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x63, 0x6f, 0x61, 0x6c, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x68,
	0x0a, 0x0f, 0x41, 0x64, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x69,
	0x63, 0x12, 0x28, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x63, 0x6f, 0x61, 0x6c, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x41, 0x64, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x53, 0x74,
	0x61, 0x74, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x64, 0x63,
	0x73, 0x2e, 0x63, 0x6f, 0x61, 0x6c, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x41,
	0x64, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x56, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x22, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x63, 0x6f, 0x61, 0x6c,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x64, 0x63, 0x73, 0x2e,
	0x63, 0x6f, 0x61, 0x6c, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x5c, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x42, 0x75, 0x6c, 0x6c, 0x73, 0x65, 0x79, 0x65, 0x12,
	0x24, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x63, 0x6f, 0x61, 0x6c, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x75, 0x6c, 0x6c, 0x73, 0x65, 0x79, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x63, 0x6f, 0x61, 0x6c,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x75, 0x6c, 0x6c,
	0x73, 0x65, 0x79, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x65,
	0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x55, 0x6e, 0x69, 0x74, 0x73,
	0x12, 0x27, 0x2e, 0x64, 0x63, 0x73, 0x2e, 0x63, 0x6f, 0x61, 0x6c, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x55, 0x6e, 0x69,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x64, 0x63, 0x73, 0x2e,
	0x63, 0x6f, 0x61, 0x6c, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x55, 0x6e, 0x69, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x57, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x44, 0x43, 0x53, 0x2d, 0x67, 0x52, 0x50, 0x43, 0x2f, 0x67, 0x6f, 0x2d,
	0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x2f, 0x64, 0x63, 0x73, 0x2f, 0x76, 0x30, 0x2f,
	0x63, 0x6f, 0x61, 0x6c, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0xaa, 0x02, 0x22, 0x52, 0x75, 0x72, 0x6f,
	0x75, 0x6e, 0x69, 0x4a, 0x6f, 0x6e, 0x65, 0x73, 0x2e, 0x44, 0x63, 0x73, 0x2e, 0x47, 0x72, 0x70,
	0x63, 0x2e, 0x56, 0x30, 0x2e, 0x43, 0x6f, 0x61, 0x6c, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dcs_coalition_v0_coalition_proto_rawDescOnce sync.Once
	file_dcs_coalition_v0_coalition_proto_rawDescData = file_dcs_coalition_v0_coalition_proto_rawDesc
)

func file_dcs_coalition_v0_coalition_proto_rawDescGZIP() []byte {
	file_dcs_coalition_v0_coalition_proto_rawDescOnce.Do(func() {
		file_dcs_coalition_v0_coalition_proto_rawDescData = protoimpl.X.CompressGZIP(file_dcs_coalition_v0_coalition_proto_rawDescData)
	})
	return file_dcs_coalition_v0_coalition_proto_rawDescData
}

var file_dcs_coalition_v0_coalition_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_dcs_coalition_v0_coalition_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_dcs_coalition_v0_coalition_proto_goTypes = []interface{}{
	(AddGroupRequest_Skill)(0),                      // 0: dcs.coalition.v0.AddGroupRequest.Skill
	(AddGroupRequest_Point_AltitudeType)(0),         // 1: dcs.coalition.v0.AddGroupRequest.Point.AltitudeType
	(AddGroupRequest_Point_PointType)(0),            // 2: dcs.coalition.v0.AddGroupRequest.Point.PointType
	(*AddGroupRequest)(nil),                         // 3: dcs.coalition.v0.AddGroupRequest
	(*AddGroupResponse)(nil),                        // 4: dcs.coalition.v0.AddGroupResponse
	(*GetStaticObjectsRequest)(nil),                 // 5: dcs.coalition.v0.GetStaticObjectsRequest
	(*GetStaticObjectsResponse)(nil),                // 6: dcs.coalition.v0.GetStaticObjectsResponse
	(*AddStaticObjectRequest)(nil),                  // 7: dcs.coalition.v0.AddStaticObjectRequest
	(*AddStaticObjectResponse)(nil),                 // 8: dcs.coalition.v0.AddStaticObjectResponse
	(*AddLinkedStaticRequest)(nil),                  // 9: dcs.coalition.v0.AddLinkedStaticRequest
	(*AddLinkedStaticResponse)(nil),                 // 10: dcs.coalition.v0.AddLinkedStaticResponse
	(*GetGroupsRequest)(nil),                        // 11: dcs.coalition.v0.GetGroupsRequest
	(*GetGroupsResponse)(nil),                       // 12: dcs.coalition.v0.GetGroupsResponse
	(*GetBullseyeRequest)(nil),                      // 13: dcs.coalition.v0.GetBullseyeRequest
	(*GetBullseyeResponse)(nil),                     // 14: dcs.coalition.v0.GetBullseyeResponse
	(*GetPlayerUnitsRequest)(nil),                   // 15: dcs.coalition.v0.GetPlayerUnitsRequest
	(*GetPlayerUnitsResponse)(nil),                  // 16: dcs.coalition.v0.GetPlayerUnitsResponse
	(*AddGroupRequest_GroundGroupTemplate)(nil),     // 17: dcs.coalition.v0.AddGroupRequest.GroundGroupTemplate
	(*AddGroupRequest_GroundUnitTemplate)(nil),      // 18: dcs.coalition.v0.AddGroupRequest.GroundUnitTemplate
	(*AddGroupRequest_ShipGroupTemplate)(nil),       // 19: dcs.coalition.v0.AddGroupRequest.ShipGroupTemplate
	(*AddGroupRequest_ShipUnitTemplate)(nil),        // 20: dcs.coalition.v0.AddGroupRequest.ShipUnitTemplate
	(*AddGroupRequest_HelicopterGroupTemplate)(nil), // 21: dcs.coalition.v0.AddGroupRequest.HelicopterGroupTemplate
	(*AddGroupRequest_HelicopterUnitTemplate)(nil),  // 22: dcs.coalition.v0.AddGroupRequest.HelicopterUnitTemplate
	(*AddGroupRequest_PlaneGroupTemplate)(nil),      // 23: dcs.coalition.v0.AddGroupRequest.PlaneGroupTemplate
	(*AddGroupRequest_PlaneUnitTemplate)(nil),       // 24: dcs.coalition.v0.AddGroupRequest.PlaneUnitTemplate
	(*AddGroupRequest_Point)(nil),                   // 25: dcs.coalition.v0.AddGroupRequest.Point
	(*AddGroupRequest_Task)(nil),                    // 26: dcs.coalition.v0.AddGroupRequest.Task
	(common.Country)(0),                             // 27: dcs.common.v0.Country
	(common.GroupCategory)(0),                       // 28: dcs.common.v0.GroupCategory
	(*common.Group)(nil),                            // 29: dcs.common.v0.Group
	(common.Coalition)(0),                           // 30: dcs.common.v0.Coalition
	(*common.Static)(nil),                           // 31: dcs.common.v0.Static
	(*common.InputPosition)(nil),                    // 32: dcs.common.v0.InputPosition
	(*common.Position)(nil),                         // 33: dcs.common.v0.Position
	(*common.Unit)(nil),                             // 34: dcs.common.v0.Unit
}
var file_dcs_coalition_v0_coalition_proto_depIdxs = []int32{
	27, // 0: dcs.coalition.v0.AddGroupRequest.country:type_name -> dcs.common.v0.Country
	28, // 1: dcs.coalition.v0.AddGroupRequest.group_category:type_name -> dcs.common.v0.GroupCategory
	17, // 2: dcs.coalition.v0.AddGroupRequest.ground_template:type_name -> dcs.coalition.v0.AddGroupRequest.GroundGroupTemplate
	19, // 3: dcs.coalition.v0.AddGroupRequest.ship_template:type_name -> dcs.coalition.v0.AddGroupRequest.ShipGroupTemplate
	21, // 4: dcs.coalition.v0.AddGroupRequest.helicopter_template:type_name -> dcs.coalition.v0.AddGroupRequest.HelicopterGroupTemplate
	23, // 5: dcs.coalition.v0.AddGroupRequest.plane_template:type_name -> dcs.coalition.v0.AddGroupRequest.PlaneGroupTemplate
	29, // 6: dcs.coalition.v0.AddGroupResponse.group:type_name -> dcs.common.v0.Group
	30, // 7: dcs.coalition.v0.GetStaticObjectsRequest.coalition:type_name -> dcs.common.v0.Coalition
	31, // 8: dcs.coalition.v0.GetStaticObjectsResponse.statics:type_name -> dcs.common.v0.Static
	27, // 9: dcs.coalition.v0.AddStaticObjectRequest.country:type_name -> dcs.common.v0.Country
	32, // 10: dcs.coalition.v0.AddStaticObjectRequest.position:type_name -> dcs.common.v0.InputPosition
	27, // 11: dcs.coalition.v0.AddLinkedStaticRequest.country:type_name -> dcs.common.v0.Country
	30, // 12: dcs.coalition.v0.GetGroupsRequest.coalition:type_name -> dcs.common.v0.Coalition
	28, // 13: dcs.coalition.v0.GetGroupsRequest.category:type_name -> dcs.common.v0.GroupCategory
	29, // 14: dcs.coalition.v0.GetGroupsResponse.groups:type_name -> dcs.common.v0.Group
	30, // 15: dcs.coalition.v0.GetBullseyeRequest.coalition:type_name -> dcs.common.v0.Coalition
	33, // 16: dcs.coalition.v0.GetBullseyeResponse.position:type_name -> dcs.common.v0.Position
	30, // 17: dcs.coalition.v0.GetPlayerUnitsRequest.coalition:type_name -> dcs.common.v0.Coalition
	34, // 18: dcs.coalition.v0.GetPlayerUnitsResponse.units:type_name -> dcs.common.v0.Unit
	32, // 19: dcs.coalition.v0.AddGroupRequest.GroundGroupTemplate.position:type_name -> dcs.common.v0.InputPosition
	25, // 20: dcs.coalition.v0.AddGroupRequest.GroundGroupTemplate.waypoints:type_name -> dcs.coalition.v0.AddGroupRequest.Point
	26, // 21: dcs.coalition.v0.AddGroupRequest.GroundGroupTemplate.tasks:type_name -> dcs.coalition.v0.AddGroupRequest.Task
	18, // 22: dcs.coalition.v0.AddGroupRequest.GroundGroupTemplate.units:type_name -> dcs.coalition.v0.AddGroupRequest.GroundUnitTemplate
	32, // 23: dcs.coalition.v0.AddGroupRequest.GroundUnitTemplate.position:type_name -> dcs.common.v0.InputPosition
	0,  // 24: dcs.coalition.v0.AddGroupRequest.GroundUnitTemplate.skill:type_name -> dcs.coalition.v0.AddGroupRequest.Skill
	32, // 25: dcs.coalition.v0.AddGroupRequest.Point.position:type_name -> dcs.common.v0.InputPosition
	1,  // 26: dcs.coalition.v0.AddGroupRequest.Point.altitude_type:type_name -> dcs.coalition.v0.AddGroupRequest.Point.AltitudeType
	2,  // 27: dcs.coalition.v0.AddGroupRequest.Point.type:type_name -> dcs.coalition.v0.AddGroupRequest.Point.PointType
	3,  // 28: dcs.coalition.v0.CoalitionService.AddGroup:input_type -> dcs.coalition.v0.AddGroupRequest
	5,  // 29: dcs.coalition.v0.CoalitionService.GetStaticObjects:input_type -> dcs.coalition.v0.GetStaticObjectsRequest
	7,  // 30: dcs.coalition.v0.CoalitionService.AddStaticObject:input_type -> dcs.coalition.v0.AddStaticObjectRequest
	9,  // 31: dcs.coalition.v0.CoalitionService.AddLinkedStatic:input_type -> dcs.coalition.v0.AddLinkedStaticRequest
	11, // 32: dcs.coalition.v0.CoalitionService.GetGroups:input_type -> dcs.coalition.v0.GetGroupsRequest
	13, // 33: dcs.coalition.v0.CoalitionService.GetBullseye:input_type -> dcs.coalition.v0.GetBullseyeRequest
	15, // 34: dcs.coalition.v0.CoalitionService.GetPlayerUnits:input_type -> dcs.coalition.v0.GetPlayerUnitsRequest
	4,  // 35: dcs.coalition.v0.CoalitionService.AddGroup:output_type -> dcs.coalition.v0.AddGroupResponse
	6,  // 36: dcs.coalition.v0.CoalitionService.GetStaticObjects:output_type -> dcs.coalition.v0.GetStaticObjectsResponse
	8,  // 37: dcs.coalition.v0.CoalitionService.AddStaticObject:output_type -> dcs.coalition.v0.AddStaticObjectResponse
	10, // 38: dcs.coalition.v0.CoalitionService.AddLinkedStatic:output_type -> dcs.coalition.v0.AddLinkedStaticResponse
	12, // 39: dcs.coalition.v0.CoalitionService.GetGroups:output_type -> dcs.coalition.v0.GetGroupsResponse
	14, // 40: dcs.coalition.v0.CoalitionService.GetBullseye:output_type -> dcs.coalition.v0.GetBullseyeResponse
	16, // 41: dcs.coalition.v0.CoalitionService.GetPlayerUnits:output_type -> dcs.coalition.v0.GetPlayerUnitsResponse
	35, // [35:42] is the sub-list for method output_type
	28, // [28:35] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_dcs_coalition_v0_coalition_proto_init() }
func file_dcs_coalition_v0_coalition_proto_init() {
	if File_dcs_coalition_v0_coalition_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dcs_coalition_v0_coalition_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_coalition_v0_coalition_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_coalition_v0_coalition_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStaticObjectsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_coalition_v0_coalition_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStaticObjectsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_coalition_v0_coalition_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddStaticObjectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_coalition_v0_coalition_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddStaticObjectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_coalition_v0_coalition_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddLinkedStaticRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_coalition_v0_coalition_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddLinkedStaticResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_coalition_v0_coalition_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGroupsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_coalition_v0_coalition_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGroupsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_coalition_v0_coalition_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBullseyeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_coalition_v0_coalition_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBullseyeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_coalition_v0_coalition_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlayerUnitsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_coalition_v0_coalition_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlayerUnitsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_coalition_v0_coalition_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGroupRequest_GroundGroupTemplate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_coalition_v0_coalition_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGroupRequest_GroundUnitTemplate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_coalition_v0_coalition_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGroupRequest_ShipGroupTemplate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_coalition_v0_coalition_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGroupRequest_ShipUnitTemplate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_coalition_v0_coalition_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGroupRequest_HelicopterGroupTemplate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_coalition_v0_coalition_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGroupRequest_HelicopterUnitTemplate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_coalition_v0_coalition_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGroupRequest_PlaneGroupTemplate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_coalition_v0_coalition_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGroupRequest_PlaneUnitTemplate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_coalition_v0_coalition_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGroupRequest_Point); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dcs_coalition_v0_coalition_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGroupRequest_Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_dcs_coalition_v0_coalition_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*AddGroupRequest_GroundTemplate)(nil),
		(*AddGroupRequest_ShipTemplate)(nil),
		(*AddGroupRequest_HelicopterTemplate)(nil),
		(*AddGroupRequest_PlaneTemplate)(nil),
	}
	file_dcs_coalition_v0_coalition_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_dcs_coalition_v0_coalition_proto_msgTypes[6].OneofWrappers = []interface{}{}
	file_dcs_coalition_v0_coalition_proto_msgTypes[14].OneofWrappers = []interface{}{}
	file_dcs_coalition_v0_coalition_proto_msgTypes[15].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dcs_coalition_v0_coalition_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dcs_coalition_v0_coalition_proto_goTypes,
		DependencyIndexes: file_dcs_coalition_v0_coalition_proto_depIdxs,
		EnumInfos:         file_dcs_coalition_v0_coalition_proto_enumTypes,
		MessageInfos:      file_dcs_coalition_v0_coalition_proto_msgTypes,
	}.Build()
	File_dcs_coalition_v0_coalition_proto = out.File
	file_dcs_coalition_v0_coalition_proto_rawDesc = nil
	file_dcs_coalition_v0_coalition_proto_goTypes = nil
	file_dcs_coalition_v0_coalition_proto_depIdxs = nil
}
